apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: default
      app.kubernetes.io/component: controller
    includeSelectors: false

images:
  - name: ghcr.io/sovereignite/shipcrew
    newName: ghcr.io/sovereignite/shipcrew
    newTag: latest
