apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-namespace-cluster-tigera-operator.yaml
  - resources/001-serviceaccount-tigera-operator-tigera-operator.yaml
  - resources/002-clusterrole-cluster-tigera-operator.yaml
  - resources/003-clusterrole-cluster-tigera-operator-secrets.yaml
  - resources/004-rolebinding-tigera-operator-tigera-operator-secrets.yaml
  - resources/005-clusterrolebinding-cluster-tigera-operator.yaml
  - resources/006-deployment-tigera-operator-tigera-operator.yaml
