# Source apiVersion: v1
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.22.2
  name: mt-broker-filter
  namespace: knative-eventing
