# Source apiVersion: rbac.authorization.k8s.io/v1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: imc-dispatcher-tls-role-binding
  namespace: knative-eventing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: imc-dispatcher-tls-role
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: imc-dispatcher
