# Source apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: eventing-controller
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.22.2
    bindings.knative.dev/exclude: "true"
    knative.dev/high-availability: "true"
  name: eventing-controller
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      app: eventing-controller
  template:
    metadata:
      labels:
        app: eventing-controller
        app.kubernetes.io/component: eventing-controller
        app.kubernetes.io/name: knative-eventing
        app.kubernetes.io/version: 1.22.2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: eventing-controller
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: METRICS_DOMAIN
              value: knative.dev/eventing
            - name: APISERVER_RA_IMAGE
              value: gcr.io/knative-releases/knative.dev/eventing/cmd/apiserver_receive_adapter@sha256:15a33e67e795c2547e0734d3397d95afa2a4266a0d76fdd896444f27e4182997
            - name: AUTH_PROXY_IMAGE
              value: gcr.io/knative-releases/knative.dev/eventing/cmd/auth_proxy@sha256:1eb7574f2c9b511be22e619b64bf5dab96e055faf69635a8fa042527979b9835
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EVENT_TRANSFORM_JSONATA_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: transform-jsonata
                  name: eventing-transformations-images
            - name: INTEGRATION_SOURCE_TIMER_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: timer-source
                  name: eventing-integrations-images
            - name: INTEGRATION_SOURCE_AWS_S3_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-s3-source
                  name: eventing-integrations-images
            - name: INTEGRATION_SOURCE_AWS_SQS_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-sqs-source
                  name: eventing-integrations-images
            - name: INTEGRATION_SOURCE_AWS_DDB_STREAMS_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-ddb-streams-source
                  name: eventing-integrations-images
            - name: INTEGRATION_SINK_LOG_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: log-sink
                  name: eventing-integrations-images
            - name: INTEGRATION_SINK_AWS_S3_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-s3-sink
                  name: eventing-integrations-images
            - name: INTEGRATION_SINK_AWS_SQS_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-sqs-sink
                  name: eventing-integrations-images
            - name: INTEGRATION_SINK_AWS_SNS_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: aws-sns-sink
                  name: eventing-integrations-images
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:866896c0d955ec7774e6c85e6349e034470ccb3317d34f08b3273c950c59eb39
          livenessProbe:
            httpGet:
              path: /health
              port: probes
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          name: eventing-controller
          ports:
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
            - containerPort: 8080
              name: probes
          readinessProbe:
            httpGet:
              path: /readiness
              port: probes
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePolicy: FallbackToLogsOnError
      enableServiceLinks: false
      serviceAccountName: eventing-controller
