# Source apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: imc-controller
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.22.2
  name: inmemorychannel-webhook
  namespace: knative-eventing
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
  selector:
    messaging.knative.dev/channel: in-memory-channel
    messaging.knative.dev/role: controller
