# Source apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: imc-dispatcher
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.22.2
    bindings.knative.dev/exclude: "true"
    knative.dev/high-availability: "true"
  name: imc-dispatcher
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      messaging.knative.dev/channel: in-memory-channel
      messaging.knative.dev/role: dispatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/component: imc-dispatcher
        app.kubernetes.io/name: knative-eventing
        app.kubernetes.io/version: 1.22.2
        messaging.knative.dev/channel: in-memory-channel
        messaging.knative.dev/role: dispatcher
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    messaging.knative.dev/channel: in-memory-channel
                    messaging.knative.dev/role: dispatcher
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: METRICS_DOMAIN
              value: knative.dev/inmemorychannel-dispatcher
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONTAINER_NAME
              value: dispatcher
            - name: MAX_IDLE_CONNS
              value: "1000"
            - name: MAX_IDLE_CONNS_PER_HOST
              value: "1000"
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:aa39224456b80b2734729450a9eb6076b13e008060a522436e2475b1ca9b058e
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          name: dispatcher
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 9090
              name: metrics
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      enableServiceLinks: false
      serviceAccountName: imc-dispatcher
