apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: keyvalidation
    app.kubernetes.io/part-of: sovereignite
  name: keyvalidation
  namespace: sovereignite-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keyvalidation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keyvalidation
        app.kubernetes.io/part-of: sovereignite
    spec:
      containers:
      - args:
        - --addr=127.0.0.1:8443
        image: ghcr.io/sovereignite/keyvalidation:v0.0.0
        name: keyvalidation
        ports:
        - containerPort: 8443
          name: grpc
          protocol: TCP
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
      serviceAccountName: keyvalidation
