name: 'ko Setup'
description: 'Setup ko build tool'
inputs:
  go-version-file:
    description: 'Path to go.mod for Go version detection'
    required: false
    default: 'go.mod'
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version-file: ${{ inputs.go-version-file }}

    - name: Setup ko
      uses: ko-build/setup-ko@v0.10
