apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- eventing.knative.dev_v1_broker_default.yaml
- eventing.knative.dev_v1_trigger_hello-display.yaml
- serving.knative.dev_v1_service_hello.yaml
- v1_namespace_sample-knative.yaml
