defaultBaseImage: gcr.io/distroless/cc-debian13
defaultPlatforms:
  - linux/amd64
builds:
  - id: keymanager
    dir: .
    main: ./cmd/keymanager
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: libp2p-init
    dir: .
    main: ./cmd/libp2p-init
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: ipfs
    dir: .
    main: ./cmd/ipfs
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: trust
    dir: .
    main: ./cmd/trust
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: discovery
    dir: .
    main: ./cmd/discovery
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: bootstrap
    dir: .
    main: ./cmd/bootstrap
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: keyvalidation
    dir: .
    main: ./cmd/keyvalidation
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
