name: 'kpt Provenance'
description: 'Generate provenance report for kpt package'
inputs:
  package_path:
    description: 'Path to kpt package directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Provenance"
      run: kpt fn eval "${{ inputs.package_path }}" -i ghcr.io/sovereignite/kpt-fn-provenance:latest --output unwrap
      shell: bash
