name: 'kpt Provenance'
description: 'Generate provenance report for kpt package'
inputs:
  package_path:
    description: 'Path to kpt package directory'
    required: true
  image:
    description: 'Provenance function image'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Provenance"
      run: kpt fn eval "${{ inputs.package_path }}" -i "${{ inputs.image }}" --output unwrap
      shell: bash
