name: 'kpt Setup'
description: 'Setup kpt CLI'
inputs:
  version:
    description: 'kpt version'
    required: false
    default: 'v1.0.0-beta.67'
runs:
  using: "composite"
  steps:
    - name: Install kpt
      run: |
        VERSION="${{ inputs.version }}"
        curl -fsSL "https://github.com/kptdev/kpt/releases/download/${VERSION}/kpt_linux_amd64-${VERSION#v}.tar.gz" | tar xz -C /usr/local/bin kpt
      shell: bash
