apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/00-crd.yaml
  - resources/10-service-account.yaml
  - resources/11-role.yaml
  - resources/12-role-binding.yaml
  - resources/20-deployment.yaml
