apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-agent
subjects:
  - kind: ServiceAccount
    name: spire-agent
    namespace: spire
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spire-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - spire.spiffe.io
    resources:
      - clusterspiffeids
      - clusterfederatedtrustdomains
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-controller-manager
subjects:
  - kind: ServiceAccount
    name: spire-controller-manager
    namespace: spire
