apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-cp-1
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/cp-1
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-cp-1
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-cp-2
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/cp-2
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-cp-2
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-cp-3
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/cp-3
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-cp-3
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-1
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/worker-1
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-1
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-2
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/worker-2
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-2
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-3
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/worker-3
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-3
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-4
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/worker-4
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-4
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-5
spec:
  parentID: spiffe://sovereignite.local/spire/server
  spiffeID: spiffe://sovereignite.local/nodes/worker-5
  selectors:
    - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-5
