apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps_v1_deployment_tigera-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_tigera-operator-secrets.yaml
- rbac.authorization.k8s.io_v1_clusterrole_tigera-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_tigera-operator.yaml
- rbac.authorization.k8s.io_v1_rolebinding_tigera-operator-secrets.yaml
- v1_namespace_tigera-operator.yaml
- v1_serviceaccount_tigera-operator.yaml
