FROM golang:1.26-bookworm AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY controllers ./controllers
RUN CGO_ENABLED=1 go build -trimpath -ldflags="-s -w" -o /out/spire-tpm-keymanager ./controllers/spire-tpm-keymanager/cmd/spire-tpm-keymanager

FROM ghcr.io/spiffe/spire-server:1.15.2 AS spire

FROM fedora:44
RUN dnf -y install ca-certificates openssl tpm2-pkcs11 tpm2-pkcs11-tools tpm2-tools \
    && dnf clean all
COPY --from=spire /opt/spire/bin/spire-server /opt/spire/bin/spire-server
COPY --from=build /out/spire-tpm-keymanager /opt/spire/plugins/spire-tpm-keymanager
USER 65532:65532
ENTRYPOINT ["/opt/spire/bin/spire-server"]
