apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    agentgateway: agentgateway
    app.kubernetes.io/instance: agentgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agentgateway
    app.kubernetes.io/version: v1.4.1
    helm.sh/chart: agentgateway-v1.4.1
  name: agentgateway
  namespace: agentgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      agentgateway: agentgateway
      app.kubernetes.io/instance: agentgateway
      app.kubernetes.io/name: agentgateway
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9092"
        prometheus.io/scrape: "true"
      labels:
        agentgateway: agentgateway
        app.kubernetes.io/instance: agentgateway
        app.kubernetes.io/name: agentgateway
    spec:
      containers:
      - env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: AGW_PROXY_IMAGE_REGISTRY
          value: cr.agentgateway.dev
        - name: AGW_PROXY_IMAGE_REPOSITORY
          value: agentgateway
        - name: AGW_LOG_LEVEL
          value: info
        - name: AGW_XDS_SERVICE_NAME
          value: agentgateway
        - name: AGW_AGENTGATEWAY_XDS_SERVICE_PORT
          value: "9978"
        - name: AGW_DISCOVERY_NAMESPACE_SELECTORS
          value: '[]'
        - name: AGW_XDS_MODE
          value: tls
        - name: AGW_GATEWAY_CLASS_PARAMETERS_REFS
          value: '{}'
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: cr.agentgateway.dev/controller:v1.4.1
        imagePullPolicy: Always
        name: controller
        ports:
        - containerPort: 9978
          name: grpc-xds-agw
          protocol: TCP
        - containerPort: 9093
          name: health
          protocol: TCP
        - containerPort: 9092
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9093
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 120
          httpGet:
            path: /readyz
            port: 9093
          initialDelaySeconds: 0
          periodSeconds: 1
      serviceAccountName: agentgateway
