apiVersion: v1
kind: Service
metadata:
  labels:
    agentgateway: agentgateway
    app.kubernetes.io/instance: agentgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agentgateway
    app.kubernetes.io/version: v1.4.1
    helm.sh/chart: agentgateway-v1.4.1
  name: agentgateway
  namespace: agentgateway-system
spec:
  ports:
  - name: grpc-xds-agw
    port: 9978
    protocol: TCP
    targetPort: grpc-xds-agw
  - name: health
    port: 9093
    protocol: TCP
    targetPort: health
  - name: metrics
    port: 9092
    protocol: TCP
    targetPort: metrics
  selector:
    agentgateway: agentgateway
    app.kubernetes.io/instance: agentgateway
    app.kubernetes.io/name: agentgateway
  type: ClusterIP
