apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    agentgateway: agentgateway
    app.kubernetes.io/instance: agentgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agentgateway
    app.kubernetes.io/version: v1.4.1
    helm.sh/chart: agentgateway-v1.4.1
  name: agentgateway
  namespace: agentgateway-system
