apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentgateway-system
resources:
- namespace.yaml
helmCharts:
- name: agentgateway
  repo: oci://cr.agentgateway.dev/charts
  version: v1.4.1
  releaseName: agentgateway
  namespace: agentgateway-system
  valuesFile: values.yaml
