apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_istio-sidecar-injector.yaml
- admissionregistration.k8s.io_v1_validatingwebhookconfiguration_istio-validator-istio-system.yaml
- admissionregistration.k8s.io_v1_validatingwebhookconfiguration_istiod-default-validator.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_authorizationpolicies.security.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_destinationrules.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_envoyfilters.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_gateways.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_peerauthentications.security.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_proxyconfigs.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_requestauthentications.security.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_serviceentries.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_sidecars.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_telemetries.telemetry.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_trafficextensions.extensions.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_virtualservices.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_wasmplugins.extensions.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_workloadentries.networking.istio.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_workloadgroups.networking.istio.io.yaml
- apps_v1_deployment_istio-egressgateway.yaml
- apps_v1_deployment_istio-ingressgateway.yaml
- apps_v1_deployment_istiod.yaml
- autoscaling_v2_horizontalpodautoscaler_istio-egressgateway.yaml
- autoscaling_v2_horizontalpodautoscaler_istio-ingressgateway.yaml
- autoscaling_v2_horizontalpodautoscaler_istiod.yaml
- rbac.authorization.k8s.io_v1_clusterrole_istio-reader-clusterrole-istio-system.yaml
- rbac.authorization.k8s.io_v1_clusterrole_istiod-clusterrole-istio-system.yaml
- rbac.authorization.k8s.io_v1_clusterrole_istiod-gateway-controller-istio-system.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_istio-reader-clusterrole-istio-system.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_istiod-clusterrole-istio-system.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_istiod-gateway-controller-istio-system.yaml
- rbac.authorization.k8s.io_v1_role_istio-egressgateway.yaml
- rbac.authorization.k8s.io_v1_role_istio-ingressgateway.yaml
- rbac.authorization.k8s.io_v1_role_istiod.yaml
- rbac.authorization.k8s.io_v1_rolebinding_istio-egressgateway.yaml
- rbac.authorization.k8s.io_v1_rolebinding_istio-ingressgateway.yaml
- rbac.authorization.k8s.io_v1_rolebinding_istiod.yaml
- v1_configmap_istio-sidecar-injector.yaml
- v1_configmap_istio-spire-integration.yaml
- v1_configmap_istio.yaml
- v1_configmap_values.yaml
- v1_namespace_istio-system.yaml
- v1_service_istio-egressgateway.yaml
- v1_service_istio-ingressgateway.yaml
- v1_service_istiod.yaml
- v1_serviceaccount_istio-egressgateway.yaml
- v1_serviceaccount_istio-ingressgateway.yaml
- v1_serviceaccount_istio-reader-service-account.yaml
- v1_serviceaccount_istiod.yaml
