apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.30.3
    helm.sh/chart: istiod-1.30.3
    release: istiod
  name: istiod
  namespace: istio-system
