apiVersion: spire.sovereignite.io/v1alpha1
kind: SPIRETPMKeyManager
metadata:
  name: sovereignite-spire-ca
  namespace: spire
spec:
  socketPath: /run/spire-tpm-keymanager/keymanager.sock
  pkcs11:
    modulePath: /usr/lib64/pkcs11/libtpm2_pkcs11.so
    tokenLabel: sovereignite-ca
  keys:
    upstreamCA: sovereignite-spire-upstream-ca
    serverCA: sovereignite-spire-server-ca
  rotation:
    svidTtl: 1h
    caTtl: 24h
    rotationWindow: 6h
