apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- adk.sovereignite.net_v1alpha1_crew_red-team.yaml
- adk.sovereignite.net_v1alpha1_crewrun_red-engagement-001.yaml
- adk.sovereignite.net_v1alpha1_mcpserver_exploit-db.yaml
- adk.sovereignite.net_v1alpha1_mcpserver_recon-tools.yaml
- adk.sovereignite.net_v1alpha1_modelbackend_gemini-pro.yaml
- v1_namespace_red-crew.yaml
