name: 'Discover Libraries'
description: 'Find all shared libraries in internal/*'
outputs:
  libraries:
    description: 'List of library names'
    value: ${{ steps.discover.outputs.libraries }}
runs:
  using: "composite"
  steps:
    - name: "Discover"
      id: discover
      run: |
        LIBRARIES=$(find internal -maxdepth 1 -type d -not -name internal -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "libraries=$LIBRARIES" >> $GITHUB_OUTPUT
      shell: bash
