apiVersion: pki.sovereignite.io/v1alpha1
kind: TPMClusterIssuer
metadata:
  name: sovereignite-local
spec:
  signerName: sovereignite.local/cert-manager
  caRef:
    name: cert-manager-local-ca
  pkcs11:
    modulePath: /usr/lib64/pkcs11/libtpm2_pkcs11.so
    tokenLabel: sovereignite-ca
    keyLabel: sovereignite-cert-manager-ca
    userPinEnv: TPM2_PKCS11_USER_PIN
  profiles:
    default:
      maxDuration: 2160h
      usages:
        - digital signature
        - key encipherment
        - server auth
        - client auth
