apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - modelbackend.yaml
  - mcpserver-content.yaml
  - mcpserver-seo.yaml
  - mcpserver-analytics.yaml
  - mcpserver-social.yaml
  - crew.yaml
  - crewrun.yaml
