apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterStaticEntry
metadata:
  name: tpm-devid-node-worker-1
spec:
  parentID: spiffe://sovereignite.local/spire/server
  selectors:
  - tpm_devid:subject:cn:sovereignite-spire-tpm-devid-worker-1
  spiffeID: spiffe://sovereignite.local/nodes/worker-1
