apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_clusterfederatedtrustdomains.spire.spiffe.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_clusterspiffeids.spire.spiffe.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_clusterstaticentries.spire.spiffe.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_controllermanagerconfigs.spire.spiffe.io.yaml
- default_spire.spiffe.io_v1alpha1_clusterspiffeid_default-workloads.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-cp-1.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-cp-2.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-cp-3.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-worker-1.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-worker-2.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-worker-3.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-worker-4.yaml
- default_spire.spiffe.io_v1alpha1_clusterstaticentry_tpm-devid-node-worker-5.yaml
- rbac.authorization.k8s.io_v1_clusterrole_spire-agent.yaml
- rbac.authorization.k8s.io_v1_clusterrole_spire-controller-manager.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_spire-agent.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_spire-controller-manager.yaml
- spire_apps_v1_daemonset_spire-agent.yaml
- spire_apps_v1_statefulset_spire-server.yaml
- spire_rbac.authorization.k8s.io_v1_role_spire-server-bundle-publisher.yaml
- spire_rbac.authorization.k8s.io_v1_rolebinding_spire-server-bundle-publisher.yaml
- spire_v1_configmap_spire-agent-bundle.yaml
- spire_v1_configmap_spire-agent-config.yaml
- spire_v1_configmap_spire-controller-manager-config.yaml
- spire_v1_configmap_spire-server-config.yaml
- spire_v1_configmap_spire-tpm-attestor-ca.yaml
- spire_v1_service_spire-server.yaml
- spire_v1_serviceaccount_spire-agent.yaml
- spire_v1_serviceaccount_spire-controller-manager.yaml
- spire_v1_serviceaccount_spire-server.yaml
- v1_namespace_spire.yaml
