apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  ports:
  - name: grpc
    port: 8081
    targetPort: grpc
  selector:
    app.kubernetes.io/name: spire-server
  type: ClusterIP
