apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - modelbackend-gemini.yaml
  - modelbackend-ollama.yaml
  - mcpserver-web-tools.yaml
  - mcpserver-local-fs.yaml
  - crew.yaml
  - crewrun.yaml
