apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-namespace-cluster-knative-eventing.yaml
  - resources/001-customresourcedefinition-cluster-apiserversources.sources.knative.dev.yaml
  - resources/002-customresourcedefinition-cluster-brokers.eventing.knative.dev.yaml
  - resources/003-customresourcedefinition-cluster-channels.messaging.knative.dev.yaml
  - resources/004-customresourcedefinition-cluster-containersources.sources.knative.dev.yaml
  - resources/005-customresourcedefinition-cluster-eventpolicies.eventing.knative.dev.yaml
  - resources/006-customresourcedefinition-cluster-eventtransforms.eventing.knative.dev.yaml
  - resources/007-customresourcedefinition-cluster-eventtypes.eventing.knative.dev.yaml
  - resources/008-customresourcedefinition-cluster-inmemorychannels.messaging.knative.dev.yaml
  - resources/009-customresourcedefinition-cluster-integrationsinks.sinks.knative.dev.yaml
  - resources/010-customresourcedefinition-cluster-integrationsources.sources.knative.dev.yaml
  - resources/011-customresourcedefinition-cluster-jobsinks.sinks.knative.dev.yaml
  - resources/012-customresourcedefinition-cluster-parallels.flows.knative.dev.yaml
  - resources/013-customresourcedefinition-cluster-pingsources.sources.knative.dev.yaml
  - resources/014-customresourcedefinition-cluster-requestreplies.eventing.knative.dev.yaml
  - resources/015-customresourcedefinition-cluster-sequences.flows.knative.dev.yaml
  - resources/016-customresourcedefinition-cluster-sinkbindings.sources.knative.dev.yaml
  - resources/017-customresourcedefinition-cluster-subscriptions.messaging.knative.dev.yaml
  - resources/018-customresourcedefinition-cluster-triggers.eventing.knative.dev.yaml
  - resources/019-serviceaccount-knative-eventing-eventing-controller.yaml
  - resources/020-serviceaccount-knative-eventing-eventing-webhook.yaml
  - resources/021-serviceaccount-knative-eventing-imc-controller.yaml
  - resources/022-serviceaccount-knative-eventing-imc-dispatcher.yaml
  - resources/023-serviceaccount-knative-eventing-job-sink.yaml
  - resources/024-serviceaccount-knative-eventing-mt-broker-filter.yaml
  - resources/025-serviceaccount-knative-eventing-mt-broker-ingress.yaml
  - resources/026-serviceaccount-knative-eventing-mt-broker-ingress-oidc.yaml
  - resources/027-serviceaccount-knative-eventing-pingsource-mt-adapter.yaml
  - resources/028-serviceaccount-knative-eventing-request-reply.yaml
  - resources/029-role-knative-eventing-imc-dispatcher-tls-role.yaml
  - resources/030-role-knative-eventing-knative-eventing-auth-proxy.yaml
  - resources/031-role-knative-eventing-knative-eventing-webhook.yaml
  - resources/032-role-knative-eventing-knative-inmemorychannel-webhook.yaml
  - resources/033-role-knative-eventing-mt-broker-filter.yaml
  - resources/034-role-knative-eventing-mt-broker-ingress.yaml
  - resources/035-clusterrole-cluster-addressable-resolver.yaml
  - resources/036-clusterrole-cluster-broker-addressable-resolver.yaml
  - resources/037-clusterrole-cluster-broker-subscriber.yaml
  - resources/038-clusterrole-cluster-builtin-podspecable-binding.yaml
  - resources/039-clusterrole-cluster-channel-addressable-resolver.yaml
  - resources/040-clusterrole-cluster-channel-subscriber.yaml
  - resources/041-clusterrole-cluster-channelable-manipulator.yaml
  - resources/042-clusterrole-cluster-crossnamespace-subscriber.yaml
  - resources/043-clusterrole-cluster-eventing-broker-filter.yaml
  - resources/044-clusterrole-cluster-eventing-broker-ingress.yaml
  - resources/045-clusterrole-cluster-eventing-config-reader.yaml
  - resources/046-clusterrole-cluster-eventing-sources-source-observer.yaml
  - resources/047-clusterrole-cluster-eventtransforms-addressable-resolver.yaml
  - resources/048-clusterrole-cluster-flows-addressable-resolver.yaml
  - resources/049-clusterrole-cluster-imc-addressable-resolver.yaml
  - resources/050-clusterrole-cluster-imc-channelable-manipulator.yaml
  - resources/051-clusterrole-cluster-imc-controller.yaml
  - resources/052-clusterrole-cluster-imc-dispatcher.yaml
  - resources/053-clusterrole-cluster-imc-subscriber.yaml
  - resources/054-clusterrole-cluster-integrationsinks-addressable-resolver.yaml
  - resources/055-clusterrole-cluster-jobsinks-addressable-resolver.yaml
  - resources/056-clusterrole-cluster-knative-bindings-namespaced-admin.yaml
  - resources/057-clusterrole-cluster-knative-eventing-controller.yaml
  - resources/058-clusterrole-cluster-knative-eventing-eventpolicy-reader.yaml
  - resources/059-clusterrole-cluster-knative-eventing-job-sink.yaml
  - resources/060-clusterrole-cluster-knative-eventing-mt-broker-filter.yaml
  - resources/061-clusterrole-cluster-knative-eventing-mt-broker-ingress.yaml
  - resources/062-clusterrole-cluster-knative-eventing-mt-channel-broker-controller.yaml
  - resources/063-clusterrole-cluster-knative-eventing-namespaced-admin.yaml
  - resources/064-clusterrole-cluster-knative-eventing-namespaced-edit.yaml
  - resources/065-clusterrole-cluster-knative-eventing-namespaced-view.yaml
  - resources/066-clusterrole-cluster-knative-eventing-pingsource-mt-adapter.yaml
  - resources/067-clusterrole-cluster-knative-eventing-request-reply.yaml
  - resources/068-clusterrole-cluster-knative-eventing-sources-controller.yaml
  - resources/069-clusterrole-cluster-knative-eventing-webhook.yaml
  - resources/070-clusterrole-cluster-knative-flows-namespaced-admin.yaml
  - resources/071-clusterrole-cluster-knative-messaging-namespaced-admin.yaml
  - resources/072-clusterrole-cluster-knative-sinks-namespaced-admin.yaml
  - resources/073-clusterrole-cluster-knative-sources-namespaced-admin.yaml
  - resources/074-clusterrole-cluster-meta-channelable-manipulator.yaml
  - resources/075-clusterrole-cluster-podspecable-binding.yaml
  - resources/076-clusterrole-cluster-service-addressable-resolver.yaml
  - resources/077-clusterrole-cluster-serving-addressable-resolver.yaml
  - resources/078-clusterrole-cluster-source-observer.yaml
  - resources/079-rolebinding-knative-eventing-eventing-webhook.yaml
  - resources/080-rolebinding-knative-eventing-imc-controller.yaml
  - resources/081-rolebinding-knative-eventing-imc-dispatcher-tls-role-binding.yaml
  - resources/082-rolebinding-knative-eventing-mt-broker-filter.yaml
  - resources/083-rolebinding-knative-eventing-mt-broker-ingress.yaml
  - resources/084-clusterrolebinding-cluster-eventing-controller.yaml
  - resources/085-clusterrolebinding-cluster-eventing-controller-crossnamespace-subscriber.yaml
  - resources/086-clusterrolebinding-cluster-eventing-controller-manipulator.yaml
  - resources/087-clusterrolebinding-cluster-eventing-controller-resolver.yaml
  - resources/088-clusterrolebinding-cluster-eventing-controller-source-observer.yaml
  - resources/089-clusterrolebinding-cluster-eventing-controller-sources-controller.yaml
  - resources/090-clusterrolebinding-cluster-eventing-mt-channel-broker-controller.yaml
  - resources/091-clusterrolebinding-cluster-eventing-webhook.yaml
  - resources/092-clusterrolebinding-cluster-eventing-webhook-podspecable-binding.yaml
  - resources/093-clusterrolebinding-cluster-eventing-webhook-resolver.yaml
  - resources/094-clusterrolebinding-cluster-imc-controller.yaml
  - resources/095-clusterrolebinding-cluster-imc-controller-resolver.yaml
  - resources/096-clusterrolebinding-cluster-imc-dispatcher.yaml
  - resources/097-clusterrolebinding-cluster-knative-eventing-job-sink.yaml
  - resources/098-clusterrolebinding-cluster-knative-eventing-mt-broker-filter.yaml
  - resources/099-clusterrolebinding-cluster-knative-eventing-mt-broker-ingress.yaml
  - resources/100-clusterrolebinding-cluster-knative-eventing-pingsource-mt-adapter.yaml
  - resources/101-clusterrolebinding-cluster-knative-eventing-request-reply.yaml
  - resources/102-configmap-knative-eventing-config-br-default-channel.yaml
  - resources/103-configmap-knative-eventing-config-br-defaults.yaml
  - resources/104-configmap-knative-eventing-config-features.yaml
  - resources/105-configmap-knative-eventing-config-imc-event-dispatcher.yaml
  - resources/106-configmap-knative-eventing-config-kreference-mapping.yaml
  - resources/107-configmap-knative-eventing-config-leader-election.yaml
  - resources/108-configmap-knative-eventing-config-logging.yaml
  - resources/109-configmap-knative-eventing-config-observability.yaml
  - resources/110-configmap-knative-eventing-config-ping-defaults.yaml
  - resources/111-configmap-knative-eventing-config-sugar.yaml
  - resources/112-configmap-knative-eventing-config-tracing.yaml
  - resources/113-configmap-knative-eventing-default-ch-webhook.yaml
  - resources/114-configmap-knative-eventing-eventing-integrations-images.yaml
  - resources/115-configmap-knative-eventing-eventing-transformations-images.yaml
  - resources/116-secret-knative-eventing-eventing-webhook-certs.yaml
  - resources/117-secret-knative-eventing-inmemorychannel-webhook-certs.yaml
  - resources/118-secret-knative-eventing-request-reply-keys.yaml
  - resources/119-service-knative-eventing-broker-filter.yaml
  - resources/120-service-knative-eventing-broker-ingress.yaml
  - resources/121-service-knative-eventing-eventing-webhook.yaml
  - resources/122-service-knative-eventing-imc-dispatcher.yaml
  - resources/123-service-knative-eventing-inmemorychannel-webhook.yaml
  - resources/124-service-knative-eventing-job-sink.yaml
  - resources/125-service-knative-eventing-request-reply.yaml
  - resources/126-deployment-knative-eventing-eventing-controller.yaml
  - resources/127-deployment-knative-eventing-eventing-webhook.yaml
  - resources/128-deployment-knative-eventing-imc-controller.yaml
  - resources/129-deployment-knative-eventing-imc-dispatcher.yaml
  - resources/130-deployment-knative-eventing-job-sink.yaml
  - resources/131-deployment-knative-eventing-mt-broker-controller.yaml
  - resources/132-deployment-knative-eventing-mt-broker-filter.yaml
  - resources/133-deployment-knative-eventing-mt-broker-ingress.yaml
  - resources/134-deployment-knative-eventing-pingsource-mt-adapter.yaml
  - resources/135-statefulset-knative-eventing-request-reply.yaml
  - resources/136-poddisruptionbudget-knative-eventing-eventing-webhook.yaml
  - resources/137-horizontalpodautoscaler-knative-eventing-broker-filter-hpa.yaml
  - resources/138-horizontalpodautoscaler-knative-eventing-broker-ingress-hpa.yaml
  - resources/139-horizontalpodautoscaler-knative-eventing-eventing-webhook.yaml
  - resources/140-mutatingwebhookconfiguration-cluster-inmemorychannel.eventing.knative.dev.yaml
  - resources/141-mutatingwebhookconfiguration-cluster-sinkbindings.webhook.sources.knative.dev.yaml
  - resources/142-mutatingwebhookconfiguration-cluster-webhook.eventing.knative.dev.yaml
  - resources/143-validatingwebhookconfiguration-cluster-config.webhook.eventing.knative.dev.yaml
  - resources/144-validatingwebhookconfiguration-cluster-validation.inmemorychannel.eventing.knative.dev.yaml
  - resources/145-validatingwebhookconfiguration-cluster-validation.webhook.eventing.knative.dev.yaml
