apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-namespace-cluster-knative-eventing.yaml
  - resources/001-customresourcedefinition-cluster-apiserversources.sources.knative.dev.yaml
  - resources/002-customresourcedefinition-cluster-brokers.eventing.knative.dev.yaml
  - resources/003-customresourcedefinition-cluster-channels.messaging.knative.dev.yaml
  - resources/004-customresourcedefinition-cluster-containersources.sources.knative.dev.yaml
  - resources/005-customresourcedefinition-cluster-eventpolicies.eventing.knative.dev.yaml
  - resources/006-customresourcedefinition-cluster-eventtransforms.eventing.knative.dev.yaml
  - resources/007-customresourcedefinition-cluster-eventtypes.eventing.knative.dev.yaml
  - resources/008-customresourcedefinition-cluster-integrationsinks.sinks.knative.dev.yaml
  - resources/009-customresourcedefinition-cluster-integrationsources.sources.knative.dev.yaml
  - resources/010-customresourcedefinition-cluster-jobsinks.sinks.knative.dev.yaml
  - resources/011-customresourcedefinition-cluster-parallels.flows.knative.dev.yaml
  - resources/012-customresourcedefinition-cluster-pingsources.sources.knative.dev.yaml
  - resources/013-customresourcedefinition-cluster-requestreplies.eventing.knative.dev.yaml
  - resources/014-customresourcedefinition-cluster-sequences.flows.knative.dev.yaml
  - resources/015-customresourcedefinition-cluster-sinkbindings.sources.knative.dev.yaml
  - resources/016-customresourcedefinition-cluster-subscriptions.messaging.knative.dev.yaml
  - resources/017-customresourcedefinition-cluster-triggers.eventing.knative.dev.yaml
  - resources/018-serviceaccount-knative-eventing-eventing-controller.yaml
  - resources/019-serviceaccount-knative-eventing-eventing-webhook.yaml
  - resources/020-serviceaccount-knative-eventing-job-sink.yaml
  - resources/021-serviceaccount-knative-eventing-pingsource-mt-adapter.yaml
  - resources/022-serviceaccount-knative-eventing-request-reply.yaml
  - resources/023-role-knative-eventing-knative-eventing-auth-proxy.yaml
  - resources/024-role-knative-eventing-knative-eventing-webhook.yaml
  - resources/025-clusterrole-cluster-addressable-resolver.yaml
  - resources/026-clusterrole-cluster-broker-addressable-resolver.yaml
  - resources/027-clusterrole-cluster-broker-subscriber.yaml
  - resources/028-clusterrole-cluster-builtin-podspecable-binding.yaml
  - resources/029-clusterrole-cluster-channel-addressable-resolver.yaml
  - resources/030-clusterrole-cluster-channel-subscriber.yaml
  - resources/031-clusterrole-cluster-channelable-manipulator.yaml
  - resources/032-clusterrole-cluster-crossnamespace-subscriber.yaml
  - resources/033-clusterrole-cluster-eventing-broker-filter.yaml
  - resources/034-clusterrole-cluster-eventing-broker-ingress.yaml
  - resources/035-clusterrole-cluster-eventing-config-reader.yaml
  - resources/036-clusterrole-cluster-eventing-sources-source-observer.yaml
  - resources/037-clusterrole-cluster-eventtransforms-addressable-resolver.yaml
  - resources/038-clusterrole-cluster-flows-addressable-resolver.yaml
  - resources/039-clusterrole-cluster-integrationsinks-addressable-resolver.yaml
  - resources/040-clusterrole-cluster-jobsinks-addressable-resolver.yaml
  - resources/041-clusterrole-cluster-knative-bindings-namespaced-admin.yaml
  - resources/042-clusterrole-cluster-knative-eventing-controller.yaml
  - resources/043-clusterrole-cluster-knative-eventing-eventpolicy-reader.yaml
  - resources/044-clusterrole-cluster-knative-eventing-job-sink.yaml
  - resources/045-clusterrole-cluster-knative-eventing-namespaced-admin.yaml
  - resources/046-clusterrole-cluster-knative-eventing-namespaced-edit.yaml
  - resources/047-clusterrole-cluster-knative-eventing-namespaced-view.yaml
  - resources/048-clusterrole-cluster-knative-eventing-pingsource-mt-adapter.yaml
  - resources/049-clusterrole-cluster-knative-eventing-request-reply.yaml
  - resources/050-clusterrole-cluster-knative-eventing-sources-controller.yaml
  - resources/051-clusterrole-cluster-knative-eventing-webhook.yaml
  - resources/052-clusterrole-cluster-knative-flows-namespaced-admin.yaml
  - resources/053-clusterrole-cluster-knative-messaging-namespaced-admin.yaml
  - resources/054-clusterrole-cluster-knative-sinks-namespaced-admin.yaml
  - resources/055-clusterrole-cluster-knative-sources-namespaced-admin.yaml
  - resources/056-clusterrole-cluster-meta-channelable-manipulator.yaml
  - resources/057-clusterrole-cluster-podspecable-binding.yaml
  - resources/058-clusterrole-cluster-service-addressable-resolver.yaml
  - resources/059-clusterrole-cluster-serving-addressable-resolver.yaml
  - resources/060-clusterrole-cluster-source-observer.yaml
  - resources/061-rolebinding-knative-eventing-eventing-webhook.yaml
  - resources/062-clusterrolebinding-cluster-eventing-controller.yaml
  - resources/063-clusterrolebinding-cluster-eventing-controller-crossnamespace-subscriber.yaml
  - resources/064-clusterrolebinding-cluster-eventing-controller-manipulator.yaml
  - resources/065-clusterrolebinding-cluster-eventing-controller-resolver.yaml
  - resources/066-clusterrolebinding-cluster-eventing-controller-source-observer.yaml
  - resources/067-clusterrolebinding-cluster-eventing-controller-sources-controller.yaml
  - resources/068-clusterrolebinding-cluster-eventing-webhook.yaml
  - resources/069-clusterrolebinding-cluster-eventing-webhook-podspecable-binding.yaml
  - resources/070-clusterrolebinding-cluster-eventing-webhook-resolver.yaml
  - resources/071-clusterrolebinding-cluster-knative-eventing-job-sink.yaml
  - resources/072-clusterrolebinding-cluster-knative-eventing-pingsource-mt-adapter.yaml
  - resources/073-clusterrolebinding-cluster-knative-eventing-request-reply.yaml
  - resources/074-configmap-knative-eventing-config-br-default-channel.yaml
  - resources/075-configmap-knative-eventing-config-br-defaults.yaml
  - resources/076-configmap-knative-eventing-config-features.yaml
  - resources/077-configmap-knative-eventing-config-kreference-mapping.yaml
  - resources/078-configmap-knative-eventing-config-leader-election.yaml
  - resources/079-configmap-knative-eventing-config-logging.yaml
  - resources/080-configmap-knative-eventing-config-observability.yaml
  - resources/081-configmap-knative-eventing-config-ping-defaults.yaml
  - resources/082-configmap-knative-eventing-config-sugar.yaml
  - resources/083-configmap-knative-eventing-config-tracing.yaml
  - resources/084-configmap-knative-eventing-default-ch-webhook.yaml
  - resources/085-configmap-knative-eventing-eventing-integrations-images.yaml
  - resources/086-configmap-knative-eventing-eventing-transformations-images.yaml
  - resources/087-secret-knative-eventing-eventing-webhook-certs.yaml
  - resources/088-secret-knative-eventing-request-reply-keys.yaml
  - resources/089-service-knative-eventing-eventing-webhook.yaml
  - resources/090-service-knative-eventing-job-sink.yaml
  - resources/091-service-knative-eventing-request-reply.yaml
  - resources/092-deployment-knative-eventing-eventing-controller.yaml
  - resources/093-deployment-knative-eventing-eventing-webhook.yaml
  - resources/094-deployment-knative-eventing-job-sink.yaml
  - resources/095-deployment-knative-eventing-pingsource-mt-adapter.yaml
  - resources/096-statefulset-knative-eventing-request-reply.yaml
  - resources/097-poddisruptionbudget-knative-eventing-eventing-webhook.yaml
  - resources/098-horizontalpodautoscaler-knative-eventing-eventing-webhook.yaml
  - resources/099-mutatingwebhookconfiguration-cluster-sinkbindings.webhook.sources.knative.dev.yaml
  - resources/100-mutatingwebhookconfiguration-cluster-webhook.eventing.knative.dev.yaml
  - resources/101-validatingwebhookconfiguration-cluster-config.webhook.eventing.knative.dev.yaml
  - resources/102-validatingwebhookconfiguration-cluster-validation.webhook.eventing.knative.dev.yaml
