apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-tpm-csr-signer
rules:
  - apiGroups:
      - pki.sovereignite.io
    resources:
      - tpmcsrsignerpolicies
      - tpmcsrsignerpolicies/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/status
      - certificatesigningrequests/approval
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - sovereignite.local/tpm-kubelet-client
      - sovereignite.local/tpm-kubelet-serving
    verbs:
      - approve
      - sign
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
