apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  external-gateways: |
    - class: istio-private
      gateway: knative-serving/knative-private
      service: knative-serving/knative-private-istio-private
      supported-features:
      - HTTPRouteRequestTimeout
  local-gateways: |
    - class: istio-private
      gateway: knative-serving/knative-private
      service: knative-serving/knative-private-istio-private
      supported-features:
      - HTTPRouteRequestTimeout
