# Source apiVersion: rbac.authorization.k8s.io/v1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: tigera-operator
  name: tigera-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - bgpconfigurations.crd.projectcalico.org
      - bgpfilters.crd.projectcalico.org
      - bgppeers.crd.projectcalico.org
      - blockaffinities.crd.projectcalico.org
      - caliconodestatuses.crd.projectcalico.org
      - clusterinformations.crd.projectcalico.org
      - felixconfigurations.crd.projectcalico.org
      - globalnetworkpolicies.crd.projectcalico.org
      - stagedglobalnetworkpolicies.crd.projectcalico.org
      - globalnetworksets.crd.projectcalico.org
      - hostendpoints.crd.projectcalico.org
      - ipamblocks.crd.projectcalico.org
      - ipamconfigs.crd.projectcalico.org
      - ipamhandles.crd.projectcalico.org
      - ippools.crd.projectcalico.org
      - ipreservations.crd.projectcalico.org
      - kubecontrollersconfigurations.crd.projectcalico.org
      - networkpolicies.crd.projectcalico.org
      - stagednetworkpolicies.crd.projectcalico.org
      - stagedkubernetesnetworkpolicies.crd.projectcalico.org
      - networksets.crd.projectcalico.org
      - tiers.crd.projectcalico.org
    resources:
      - customresourcedefinitions
    verbs:
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - bgpconfigurations.projectcalico.org
      - bgpfilters.projectcalico.org
      - bgppeers.projectcalico.org
      - blockaffinities.projectcalico.org
      - caliconodestatuses.projectcalico.org
      - clusterinformations.projectcalico.org
      - felixconfigurations.projectcalico.org
      - globalnetworkpolicies.projectcalico.org
      - stagedglobalnetworkpolicies.projectcalico.org
      - globalnetworksets.projectcalico.org
      - hostendpoints.projectcalico.org
      - ipamblocks.projectcalico.org
      - ipamconfigurations.projectcalico.org
      - ipamhandles.projectcalico.org
      - ippools.projectcalico.org
      - ipreservations.projectcalico.org
      - kubecontrollersconfigurations.projectcalico.org
      - networkpolicies.projectcalico.org
      - stagednetworkpolicies.projectcalico.org
      - stagedkubernetesnetworkpolicies.projectcalico.org
      - networksets.projectcalico.org
      - tiers.projectcalico.org
    resources:
      - customresourcedefinitions
    verbs:
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - apiservers.operator.tigera.io
      - gatewayapis.operator.tigera.io
      - imagesets.operator.tigera.io
      - installations.operator.tigera.io
      - tigerastatuses.operator.tigera.io
      - whiskers.operator.tigera.io
      - goldmanes.operator.tigera.io
      - managementclusterconnections.operator.tigera.io
      - istios.operator.tigera.io
    resources:
      - customresourcedefinitions
    verbs:
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - clusternetworkpolicies.policy.networking.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - podtemplates
      - services
      - endpoints
      - events
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - ""
    resources:
      - resourcequotas
      - secrets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - calico-critical-pods
      - tigera-critical-pods
    resources:
      - resourcequotas
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
      - list
      - watch
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - bind
      - escalate
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch
  - apiGroups:
      - apps
    resourceNames:
      - tigera-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.tigera.io
    resources:
      - apiservers
      - apiservers/finalizers
      - apiservers/status
      - gatewayapis
      - gatewayapis/finalizers
      - goldmanes
      - goldmanes/finalizers
      - goldmanes/status
      - imagesets
      - installations
      - installations/finalizers
      - installations/status
      - managementclusterconnections
      - managementclusterconnections/finalizers
      - managementclusterconnections/status
      - tigerastatuses
      - tigerastatuses/status
      - tigerastatuses/finalizers
      - whiskers
      - whiskers/finalizers
      - whiskers/status
      - istios
      - istios/finalizers
      - istios/status
    verbs:
      - get
      - list
      - update
      - patch
      - watch
  - apiGroups:
      - operator.tigera.io
    resources:
      - tigerastatuses
    verbs:
      - create
      - delete
  - apiGroups:
      - operator.tigera.io
    resources:
      - installations
      - apiservers
      - whiskers
      - goldmanes
    verbs:
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - crd.projectcalico.org
      - projectcalico.org
    resources:
      - felixconfigurations
      - bgpconfigurations
      - ippools
    verbs:
      - create
      - patch
      - list
      - get
      - watch
  - apiGroups:
      - crd.projectcalico.org
      - projectcalico.org
    resources:
      - kubecontrollersconfigurations
      - bgpconfigurations
      - clusterinformations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - projectcalico.org
    resources:
      - ippools
    verbs:
      - create
      - update
      - delete
      - patch
      - get
      - list
      - watch
  - apiGroups:
      - projectcalico.org
    resources:
      - ipamconfigurations
      - clusterinformations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - envoy-gateway-topology-injector.tigera-gateway
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - update
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - istiod-default-validator
      - istio-validator-calico-system
    resources:
      - validatingwebhookconfigurations
    verbs:
      - update
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingadmissionpolicies
      - validatingadmissionpolicybindings
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
    verbs:
      - list
      - watch
      - update
      - get
      - create
      - delete
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingadmissionpolicies
      - mutatingadmissionpolicybindings
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resourceNames:
      - tigera-operator
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - projectcalico.org
    resources:
      - networkpolicies
      - globalnetworkpolicies
      - networksets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - projectcalico.org
    resourceNames:
      - calico-system.*
    resources:
      - tier.networkpolicies
      - tier.globalnetworkpolicies
    verbs:
      - list
      - watch
      - get
      - create
      - update
      - delete
  - apiGroups:
      - projectcalico.org
    resources:
      - tier.networkpolicies
      - tier.globalnetworkpolicies
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - projectcalico.org
    resourceNames:
      - calico-system
    resources:
      - tiers
    verbs:
      - get
      - delete
      - update
  - apiGroups:
      - projectcalico.org
    resources:
      - tiers
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resourceNames:
      - backendlbpolicies.gateway.networking.k8s.io
      - backendtlspolicies.gateway.networking.k8s.io
      - gatewayclasses.gateway.networking.k8s.io
      - gateways.gateway.networking.k8s.io
      - grpcroutes.gateway.networking.k8s.io
      - httproutes.gateway.networking.k8s.io
      - referencegrants.gateway.networking.k8s.io
      - tcproutes.gateway.networking.k8s.io
      - tlsroutes.gateway.networking.k8s.io
      - udproutes.gateway.networking.k8s.io
      - xbackendtrafficpolicies.gateway.networking.x-k8s.io
      - listenersets.gateway.networking.k8s.io
      - xmeshes.gateway.networking.x-k8s.io
      - backends.gateway.envoyproxy.io
      - backendtrafficpolicies.gateway.envoyproxy.io
      - clienttrafficpolicies.gateway.envoyproxy.io
      - envoyextensionpolicies.gateway.envoyproxy.io
      - envoypatchpolicies.gateway.envoyproxy.io
      - envoyproxies.gateway.envoyproxy.io
      - httproutefilters.gateway.envoyproxy.io
      - securitypolicies.gateway.envoyproxy.io
    resources:
      - customresourcedefinitions
    verbs:
      - update
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
    verbs:
      - create
      - update
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - gateway.envoyproxy.io
    resources:
      - envoyproxies
    verbs:
      - create
      - update
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - batch
    resourceNames:
      - tigera-gateway-api-gateway-helm-certgen
    resources:
      - jobs
    verbs:
      - update
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstancemigrations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resourceNames:
      - istiod
    resources:
      - horizontalpodautoscalers
    verbs:
      - update
  - apiGroups:
      - migration.projectcalico.org
    resources:
      - datastoremigrations
    verbs:
      - get
      - list
      - watch
