apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/name: knative-operator
    app.kubernetes.io/version: 1.22.1
  name: operator-webhook
  namespace: knative-operator
spec:
  selector:
    matchLabels:
      app: operator-webhook
      role: operator-webhook
  template:
    metadata:
      labels:
        app: operator-webhook
        app.kubernetes.io/component: operator-webhook
        app.kubernetes.io/name: knative-operator
        app.kubernetes.io/version: 1.22.1
        role: operator-webhook
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: operator-webhook
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: WEBHOOK_NAME
          value: operator-webhook
        - name: WEBHOOK_PORT
          value: "8443"
        - name: WEBHOOK_SECRET_NAME
          value: operator-webhook-certs
        - name: METRICS_DOMAIN
          value: knative.dev/operator
        - name: KUBERNETES_MIN_VERSION
          value: ""
        image: gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:95d1a4fc8cd0b9512ed518a5bffe65b6807a53eb53c61f5e44b76366dcb4e79d
        livenessProbe:
          failureThreshold: 6
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 1
        name: operator-webhook
        ports:
        - containerPort: 9090
          name: metrics
        - containerPort: 8008
          name: profiling
        - containerPort: 8443
          name: https-webhook
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: k-kubelet-probe
              value: webhook
            port: 8443
            scheme: HTTPS
          periodSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: operator-webhook
      terminationGracePeriodSeconds: 300
