apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_cert-manager-webhook.yaml
- admissionregistration.k8s.io_v1_validatingwebhookconfiguration_cert-manager-webhook.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_certificaterequests.cert-manager.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_certificates.cert-manager.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_challenges.acme.cert-manager.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_clusterissuers.cert-manager.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_issuers.cert-manager.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_orders.acme.cert-manager.io.yaml
- cert-manager_apps_v1_deployment_cert-manager-cainjector.yaml
- cert-manager_apps_v1_deployment_cert-manager-webhook.yaml
- cert-manager_apps_v1_deployment_cert-manager.yaml
- cert-manager_rbac.authorization.k8s.io_v1_role_cert-manager-webhook:dynamic-serving.yaml
- cert-manager_rbac.authorization.k8s.io_v1_rolebinding_cert-manager-webhook:dynamic-serving.yaml
- cert-manager_v1_service_cert-manager-cainjector.yaml
- cert-manager_v1_service_cert-manager-webhook.yaml
- cert-manager_v1_service_cert-manager.yaml
- cert-manager_v1_serviceaccount_cert-manager-cainjector.yaml
- cert-manager_v1_serviceaccount_cert-manager-webhook.yaml
- cert-manager_v1_serviceaccount_cert-manager.yaml
- kube-system_rbac.authorization.k8s.io_v1_role_cert-manager-cainjector:leaderelection.yaml
- kube-system_rbac.authorization.k8s.io_v1_role_cert-manager:leaderelection.yaml
- kube-system_rbac.authorization.k8s.io_v1_rolebinding_cert-manager-cainjector:leaderelection.yaml
- kube-system_rbac.authorization.k8s.io_v1_rolebinding_cert-manager:leaderelection.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-cainjector.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-cluster-view.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-approve:cert-manager-io.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-certificates.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-certificatesigningrequests.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-challenges.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-clusterissuers.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-ingress-shim.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-issuers.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-controller-orders.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-edit.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-view.yaml
- rbac.authorization.k8s.io_v1_clusterrole_cert-manager-webhook:subjectaccessreviews.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-cainjector.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-approve:cert-manager-io.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-certificates.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-certificatesigningrequests.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-challenges.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-clusterissuers.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-ingress-shim.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-issuers.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-controller-orders.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_cert-manager-webhook:subjectaccessreviews.yaml
- v1_namespace_cert-manager.yaml
