# Source apiVersion: rbac.authorization.k8s.io/v1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: net-gateway-api
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.22.1
    networking.knative.dev/ingress-provider: net-gateway-api
    serving.knative.dev/controller: "true"
  name: knative-gateway-api-core
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - referencegrants
      - referencepolicies
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - update
      - patch
      - watch
