apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-namespace-cluster-cert-manager.yaml
  - resources/001-customresourcedefinition-cluster-certificaterequests.cert-manager.io.yaml
  - resources/002-customresourcedefinition-cluster-certificates.cert-manager.io.yaml
  - resources/003-customresourcedefinition-cluster-challenges.acme.cert-manager.io.yaml
  - resources/004-customresourcedefinition-cluster-clusterissuers.cert-manager.io.yaml
  - resources/005-customresourcedefinition-cluster-issuers.cert-manager.io.yaml
  - resources/006-customresourcedefinition-cluster-orders.acme.cert-manager.io.yaml
  - resources/007-serviceaccount-cert-manager-cert-manager.yaml
  - resources/008-serviceaccount-cert-manager-cert-manager-cainjector.yaml
  - resources/009-serviceaccount-cert-manager-cert-manager-webhook.yaml
  - resources/010-role-cert-manager-cert-manager-webhook-dynamic-serving.yaml
  - resources/011-role-kube-system-cert-manager-cainjector-leaderelection.yaml
  - resources/012-role-kube-system-cert-manager-leaderelection.yaml
  - resources/013-clusterrole-cluster-cert-manager-cainjector.yaml
  - resources/014-clusterrole-cluster-cert-manager-cluster-view.yaml
  - resources/015-clusterrole-cluster-cert-manager-controller-approve-cert-manager-io.yaml
  - resources/016-clusterrole-cluster-cert-manager-controller-certificates.yaml
  - resources/017-clusterrole-cluster-cert-manager-controller-certificatesigningrequests.yaml
  - resources/018-clusterrole-cluster-cert-manager-controller-challenges.yaml
  - resources/019-clusterrole-cluster-cert-manager-controller-clusterissuers.yaml
  - resources/020-clusterrole-cluster-cert-manager-controller-ingress-shim.yaml
  - resources/021-clusterrole-cluster-cert-manager-controller-issuers.yaml
  - resources/022-clusterrole-cluster-cert-manager-controller-orders.yaml
  - resources/023-clusterrole-cluster-cert-manager-edit.yaml
  - resources/024-clusterrole-cluster-cert-manager-view.yaml
  - resources/025-clusterrole-cluster-cert-manager-webhook-subjectaccessreviews.yaml
  - resources/026-rolebinding-cert-manager-cert-manager-webhook-dynamic-serving.yaml
  - resources/027-rolebinding-kube-system-cert-manager-cainjector-leaderelection.yaml
  - resources/028-rolebinding-kube-system-cert-manager-leaderelection.yaml
  - resources/029-clusterrolebinding-cluster-cert-manager-cainjector.yaml
  - resources/030-clusterrolebinding-cluster-cert-manager-controller-approve-cert-manager-io.yaml
  - resources/031-clusterrolebinding-cluster-cert-manager-controller-certificates.yaml
  - resources/032-clusterrolebinding-cluster-cert-manager-controller-certificatesigningrequests.yaml
  - resources/033-clusterrolebinding-cluster-cert-manager-controller-challenges.yaml
  - resources/034-clusterrolebinding-cluster-cert-manager-controller-clusterissuers.yaml
  - resources/035-clusterrolebinding-cluster-cert-manager-controller-ingress-shim.yaml
  - resources/036-clusterrolebinding-cluster-cert-manager-controller-issuers.yaml
  - resources/037-clusterrolebinding-cluster-cert-manager-controller-orders.yaml
  - resources/038-clusterrolebinding-cluster-cert-manager-webhook-subjectaccessreviews.yaml
  - resources/039-service-cert-manager-cert-manager.yaml
  - resources/040-service-cert-manager-cert-manager-cainjector.yaml
  - resources/041-service-cert-manager-cert-manager-webhook.yaml
  - resources/042-deployment-cert-manager-cert-manager.yaml
  - resources/043-deployment-cert-manager-cert-manager-cainjector.yaml
  - resources/044-deployment-cert-manager-cert-manager-webhook.yaml
  - resources/045-mutatingwebhookconfiguration-cluster-cert-manager-webhook.yaml
  - resources/046-validatingwebhookconfiguration-cluster-cert-manager-webhook.yaml
