apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tpm-csr-signer
  namespace: sovereignite-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-tpm-csr-signer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-tpm-csr-signer
    spec:
      serviceAccountName: k8s-tpm-csr-signer
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
        kubernetes.io/hostname: cp-1
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: controller
          image: ghcr.io/sovereignite/k8s-tpm-csr-signer:v0.1.0
          args:
            - --leader-election-namespace=sovereignite-system
          env:
            - name: TPM2_PKCS11_STORE
              value: /var/lib/sovereignite/tpm2-pkcs11
            - name: TPM2TOOLS_TCTI
              value: device:/dev/tpmrm0
            - name: TSS2_TCTI
              value: device:/dev/tpmrm0
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tpmrm
              mountPath: /dev/tpmrm0
            - name: tpm2-pkcs11
              mountPath: /var/lib/sovereignite/tpm2-pkcs11
            - name: tpm2-tss-run
              mountPath: /run/tpm2-tss
            - name: tpm2-tss-system
              mountPath: /var/lib/tpm2-tss
            - name: tpm2-tss-home
              mountPath: /root/.local
      volumes:
        - name: tpmrm
          hostPath:
            path: /dev/tpmrm0
            type: CharDevice
        - name: tpm2-pkcs11
          hostPath:
            path: /var/lib/sovereignite/tpm2-pkcs11
            type: Directory
        - name: tpm2-tss-run
          emptyDir: {}
        - name: tpm2-tss-system
          emptyDir: {}
        - name: tpm2-tss-home
          emptyDir: {}
