apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/00-crd-clusterfederatedtrustdomains.yaml
  - resources/00-crd-clusterspiffeids.yaml
  - resources/00-crd-clusterstaticentries.yaml
  - resources/00-crd-controllermanagerconfigs.yaml
  - resources/00-namespace.yaml
  - resources/10-service-accounts.yaml
  - resources/20-rbac.yaml
  - resources/30-server-config.yaml
  - resources/31-agent-bundle-configmap.yaml
  - resources/32-controller-manager-config.yaml
  - resources/40-agent-config.yaml
  - resources/50-server.yaml
  - resources/60-agent.yaml
  - resources/70-registration-policy.yaml
  - resources/71-node-aliases.yaml
