apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/00-namespace.yaml
  - resources/10-service-accounts.yaml
  - resources/20-rbac.yaml
  - resources/30-server-config.yaml
  - resources/35-tpm-attestor-ca.yaml
  - resources/40-agent-config.yaml
  - resources/50-server.yaml
  - resources/60-agent.yaml
  - resources/70-registration-policy.yaml
