apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-clusterrole-cluster-knative-gateway-api-admin.yaml
  - resources/001-clusterrole-cluster-knative-gateway-api-core.yaml
  - resources/002-configmap-knative-serving-config-gateway.yaml
  - resources/003-secret-knative-serving-net-gateway-api-webhook-certs.yaml
  - resources/004-service-knative-serving-net-gateway-api-webhook.yaml
  - resources/005-deployment-knative-serving-net-gateway-api-controller.yaml
  - resources/006-deployment-knative-serving-net-gateway-api-webhook.yaml
  - resources/007-validatingwebhookconfiguration-cluster-config.webhook.gateway-api.networking.internal.knative.dev.yaml
