apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - modelbackend.yaml
  - mcpserver-recon.yaml
  - mcpserver-exploit.yaml
  - crew.yaml
  - crewrun.yaml
