apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/000-namespace-cluster-knative-serving.yaml
  - resources/001-customresourcedefinition-cluster-certificates.networking.internal.knative.dev.yaml
  - resources/002-customresourcedefinition-cluster-clusterdomainclaims.networking.internal.knative.dev.yaml
  - resources/003-customresourcedefinition-cluster-configurations.serving.knative.dev.yaml
  - resources/004-customresourcedefinition-cluster-domainmappings.serving.knative.dev.yaml
  - resources/005-customresourcedefinition-cluster-images.caching.internal.knative.dev.yaml
  - resources/006-customresourcedefinition-cluster-ingresses.networking.internal.knative.dev.yaml
  - resources/007-customresourcedefinition-cluster-metrics.autoscaling.internal.knative.dev.yaml
  - resources/008-customresourcedefinition-cluster-podautoscalers.autoscaling.internal.knative.dev.yaml
  - resources/009-customresourcedefinition-cluster-revisions.serving.knative.dev.yaml
  - resources/010-customresourcedefinition-cluster-routes.serving.knative.dev.yaml
  - resources/011-customresourcedefinition-cluster-serverlessservices.networking.internal.knative.dev.yaml
  - resources/012-customresourcedefinition-cluster-services.serving.knative.dev.yaml
  - resources/013-serviceaccount-knative-serving-activator.yaml
  - resources/014-serviceaccount-knative-serving-controller.yaml
  - resources/015-role-knative-serving-knative-serving-activator.yaml
  - resources/016-clusterrole-cluster-knative-serving-activator-cluster.yaml
  - resources/017-clusterrole-cluster-knative-serving-addressable-resolver.yaml
  - resources/018-clusterrole-cluster-knative-serving-admin.yaml
  - resources/019-clusterrole-cluster-knative-serving-aggregated-addressable-resolver.yaml
  - resources/020-clusterrole-cluster-knative-serving-core.yaml
  - resources/021-clusterrole-cluster-knative-serving-namespaced-admin.yaml
  - resources/022-clusterrole-cluster-knative-serving-namespaced-edit.yaml
  - resources/023-clusterrole-cluster-knative-serving-namespaced-view.yaml
  - resources/024-clusterrole-cluster-knative-serving-podspecable-binding.yaml
  - resources/025-rolebinding-knative-serving-knative-serving-activator.yaml
  - resources/026-clusterrolebinding-cluster-knative-serving-activator-cluster.yaml
  - resources/027-clusterrolebinding-cluster-knative-serving-controller-addressable-resolver.yaml
  - resources/028-clusterrolebinding-cluster-knative-serving-controller-admin.yaml
  - resources/029-configmap-knative-serving-config-autoscaler.yaml
  - resources/030-configmap-knative-serving-config-certmanager.yaml
  - resources/031-configmap-knative-serving-config-defaults.yaml
  - resources/032-configmap-knative-serving-config-deployment.yaml
  - resources/033-configmap-knative-serving-config-domain.yaml
  - resources/034-configmap-knative-serving-config-features.yaml
  - resources/035-configmap-knative-serving-config-gc.yaml
  - resources/036-configmap-knative-serving-config-leader-election.yaml
  - resources/037-configmap-knative-serving-config-logging.yaml
  - resources/038-configmap-knative-serving-config-network.yaml
  - resources/039-configmap-knative-serving-config-observability.yaml
  - resources/040-configmap-knative-serving-config-tracing.yaml
  - resources/041-secret-knative-serving-webhook-certs.yaml
  - resources/042-service-knative-serving-activator-service.yaml
  - resources/043-service-knative-serving-autoscaler.yaml
  - resources/044-service-knative-serving-controller.yaml
  - resources/045-service-knative-serving-webhook.yaml
  - resources/046-deployment-knative-serving-activator.yaml
  - resources/047-deployment-knative-serving-autoscaler.yaml
  - resources/048-deployment-knative-serving-controller.yaml
  - resources/049-deployment-knative-serving-webhook.yaml
  - resources/050-poddisruptionbudget-knative-serving-activator-pdb.yaml
  - resources/051-poddisruptionbudget-knative-serving-webhook-pdb.yaml
  - resources/052-horizontalpodautoscaler-knative-serving-activator.yaml
  - resources/053-horizontalpodautoscaler-knative-serving-webhook.yaml
  - resources/054-image-knative-serving-queue-proxy.yaml
  - resources/055-certificate-knative-serving-routing-serving-certs.yaml
  - resources/056-mutatingwebhookconfiguration-cluster-webhook.serving.knative.dev.yaml
  - resources/057-validatingwebhookconfiguration-cluster-config.webhook.serving.knative.dev.yaml
  - resources/058-validatingwebhookconfiguration-cluster-validation.webhook.serving.knative.dev.yaml
