apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: libp2p-init
    app.kubernetes.io/part-of: sovereignite
  name: libp2p-init
  namespace: sovereignite-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: libp2p-init
  template:
    metadata:
      labels:
        app.kubernetes.io/name: libp2p-init
        app.kubernetes.io/part-of: sovereignite
    spec:
      containers:
      - args:
        - --state-root=/var/lib/sovereignite/identity
        - --runtime-root=/run/sovereignite/identity
        image: ghcr.io/sovereignite/libp2p-init:v0.0.0
        name: libp2p-init
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/lib/sovereignite/identity
          name: identity-state
        - mountPath: /run/sovereignite/identity
          name: identity-runtime
        - mountPath: /run/sovereignite/keymanager
          name: keymanager-runtime
          readOnly: true
        - mountPath: /run/dbus/system_bus_socket
          name: dbus-socket
          readOnly: true
      initContainers:
      - command:
        - sh
        - -c
        - test -f /run/sovereignite/keymanager/ready.json || exit 1
        image: busybox:latest
        name: wait-keymanager
        volumeMounts:
        - mountPath: /run/sovereignite/keymanager
          name: keymanager-runtime
          readOnly: true
      serviceAccountName: libp2p-init
      volumes:
      - hostPath:
          path: /var/lib/sovereignite/identity
          type: DirectoryOrCreate
        name: identity-state
      - emptyDir: {}
        name: identity-runtime
      - hostPath:
          path: /run/sovereignite/keymanager
          type: Directory
        name: keymanager-runtime
      - hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
        name: dbus-socket
