// SPDX-License-Identifier: GPL-2.0-only
//
// Copyright (C) 2026 Sovereignite contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sovereignite/v1/sovereignite.proto

package sovereignitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKeyType int32

const (
	PublicKeyType_PUBLIC_KEY_TYPE_UNSPECIFIED PublicKeyType = 0
	PublicKeyType_PUBLIC_KEY_TYPE_RSA         PublicKeyType = 1
	PublicKeyType_PUBLIC_KEY_TYPE_ED25519     PublicKeyType = 2
	PublicKeyType_PUBLIC_KEY_TYPE_SECP256K1   PublicKeyType = 3
	PublicKeyType_PUBLIC_KEY_TYPE_ECDSA       PublicKeyType = 4
)

// Enum value maps for PublicKeyType.
var (
	PublicKeyType_name = map[int32]string{
		0: "PUBLIC_KEY_TYPE_UNSPECIFIED",
		1: "PUBLIC_KEY_TYPE_RSA",
		2: "PUBLIC_KEY_TYPE_ED25519",
		3: "PUBLIC_KEY_TYPE_SECP256K1",
		4: "PUBLIC_KEY_TYPE_ECDSA",
	}
	PublicKeyType_value = map[string]int32{
		"PUBLIC_KEY_TYPE_UNSPECIFIED": 0,
		"PUBLIC_KEY_TYPE_RSA":         1,
		"PUBLIC_KEY_TYPE_ED25519":     2,
		"PUBLIC_KEY_TYPE_SECP256K1":   3,
		"PUBLIC_KEY_TYPE_ECDSA":       4,
	}
)

func (x PublicKeyType) Enum() *PublicKeyType {
	p := new(PublicKeyType)
	*p = x
	return p
}

func (x PublicKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_sovereignite_v1_sovereignite_proto_enumTypes[0].Descriptor()
}

func (PublicKeyType) Type() protoreflect.EnumType {
	return &file_sovereignite_v1_sovereignite_proto_enumTypes[0]
}

func (x PublicKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicKeyType.Descriptor instead.
func (PublicKeyType) EnumDescriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{0}
}

type IdentityPhase int32

const (
	IdentityPhase_IDENTITY_PHASE_UNSPECIFIED IdentityPhase = 0
	IdentityPhase_IDENTITY_PHASE_PENDING     IdentityPhase = 1
	IdentityPhase_IDENTITY_PHASE_ACTIVE      IdentityPhase = 2
	IdentityPhase_IDENTITY_PHASE_REVOKED     IdentityPhase = 3
)

// Enum value maps for IdentityPhase.
var (
	IdentityPhase_name = map[int32]string{
		0: "IDENTITY_PHASE_UNSPECIFIED",
		1: "IDENTITY_PHASE_PENDING",
		2: "IDENTITY_PHASE_ACTIVE",
		3: "IDENTITY_PHASE_REVOKED",
	}
	IdentityPhase_value = map[string]int32{
		"IDENTITY_PHASE_UNSPECIFIED": 0,
		"IDENTITY_PHASE_PENDING":     1,
		"IDENTITY_PHASE_ACTIVE":      2,
		"IDENTITY_PHASE_REVOKED":     3,
	}
)

func (x IdentityPhase) Enum() *IdentityPhase {
	p := new(IdentityPhase)
	*p = x
	return p
}

func (x IdentityPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_sovereignite_v1_sovereignite_proto_enumTypes[1].Descriptor()
}

func (IdentityPhase) Type() protoreflect.EnumType {
	return &file_sovereignite_v1_sovereignite_proto_enumTypes[1]
}

func (x IdentityPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityPhase.Descriptor instead.
func (IdentityPhase) EnumDescriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{1}
}

type ConditionStatus int32

const (
	ConditionStatus_CONDITION_STATUS_UNSPECIFIED ConditionStatus = 0
	ConditionStatus_CONDITION_STATUS_TRUE        ConditionStatus = 1
	ConditionStatus_CONDITION_STATUS_FALSE       ConditionStatus = 2
	ConditionStatus_CONDITION_STATUS_UNKNOWN     ConditionStatus = 3
)

// Enum value maps for ConditionStatus.
var (
	ConditionStatus_name = map[int32]string{
		0: "CONDITION_STATUS_UNSPECIFIED",
		1: "CONDITION_STATUS_TRUE",
		2: "CONDITION_STATUS_FALSE",
		3: "CONDITION_STATUS_UNKNOWN",
	}
	ConditionStatus_value = map[string]int32{
		"CONDITION_STATUS_UNSPECIFIED": 0,
		"CONDITION_STATUS_TRUE":        1,
		"CONDITION_STATUS_FALSE":       2,
		"CONDITION_STATUS_UNKNOWN":     3,
	}
)

func (x ConditionStatus) Enum() *ConditionStatus {
	p := new(ConditionStatus)
	*p = x
	return p
}

func (x ConditionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sovereignite_v1_sovereignite_proto_enumTypes[2].Descriptor()
}

func (ConditionStatus) Type() protoreflect.EnumType {
	return &file_sovereignite_v1_sovereignite_proto_enumTypes[2]
}

func (x ConditionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionStatus.Descriptor instead.
func (ConditionStatus) EnumDescriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{2}
}

type AdoptionState int32

const (
	AdoptionState_ADOPTION_STATE_UNSPECIFIED AdoptionState = 0
	AdoptionState_ADOPTION_STATE_UNADOPTED   AdoptionState = 1
	AdoptionState_ADOPTION_STATE_ADOPTED     AdoptionState = 2
)

// Enum value maps for AdoptionState.
var (
	AdoptionState_name = map[int32]string{
		0: "ADOPTION_STATE_UNSPECIFIED",
		1: "ADOPTION_STATE_UNADOPTED",
		2: "ADOPTION_STATE_ADOPTED",
	}
	AdoptionState_value = map[string]int32{
		"ADOPTION_STATE_UNSPECIFIED": 0,
		"ADOPTION_STATE_UNADOPTED":   1,
		"ADOPTION_STATE_ADOPTED":     2,
	}
)

func (x AdoptionState) Enum() *AdoptionState {
	p := new(AdoptionState)
	*p = x
	return p
}

func (x AdoptionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdoptionState) Descriptor() protoreflect.EnumDescriptor {
	return file_sovereignite_v1_sovereignite_proto_enumTypes[3].Descriptor()
}

func (AdoptionState) Type() protoreflect.EnumType {
	return &file_sovereignite_v1_sovereignite_proto_enumTypes[3]
}

func (x AdoptionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdoptionState.Descriptor instead.
func (AdoptionState) EnumDescriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{3}
}

type BootstrapState int32

const (
	BootstrapState_BOOTSTRAP_STATE_UNSPECIFIED BootstrapState = 0
	BootstrapState_BOOTSTRAP_STATE_NOT_STARTED BootstrapState = 1
	BootstrapState_BOOTSTRAP_STATE_IN_PROGRESS BootstrapState = 2
	BootstrapState_BOOTSTRAP_STATE_COMPLETE    BootstrapState = 3
	BootstrapState_BOOTSTRAP_STATE_FAILED      BootstrapState = 4
)

// Enum value maps for BootstrapState.
var (
	BootstrapState_name = map[int32]string{
		0: "BOOTSTRAP_STATE_UNSPECIFIED",
		1: "BOOTSTRAP_STATE_NOT_STARTED",
		2: "BOOTSTRAP_STATE_IN_PROGRESS",
		3: "BOOTSTRAP_STATE_COMPLETE",
		4: "BOOTSTRAP_STATE_FAILED",
	}
	BootstrapState_value = map[string]int32{
		"BOOTSTRAP_STATE_UNSPECIFIED": 0,
		"BOOTSTRAP_STATE_NOT_STARTED": 1,
		"BOOTSTRAP_STATE_IN_PROGRESS": 2,
		"BOOTSTRAP_STATE_COMPLETE":    3,
		"BOOTSTRAP_STATE_FAILED":      4,
	}
)

func (x BootstrapState) Enum() *BootstrapState {
	p := new(BootstrapState)
	*p = x
	return p
}

func (x BootstrapState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BootstrapState) Descriptor() protoreflect.EnumDescriptor {
	return file_sovereignite_v1_sovereignite_proto_enumTypes[4].Descriptor()
}

func (BootstrapState) Type() protoreflect.EnumType {
	return &file_sovereignite_v1_sovereignite_proto_enumTypes[4]
}

func (x BootstrapState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BootstrapState.Descriptor instead.
func (BootstrapState) EnumDescriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{4}
}

// PublicKey contains public device-key material only. tpm_handle is the sole
// reference to the corresponding non-exportable TPM private material.
type PublicKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            PublicKeyType          `protobuf:"varint,1,opt,name=type,proto3,enum=sovereignite.v1.PublicKeyType" json:"type,omitempty"`
	PublicRawBase64 string                 `protobuf:"bytes,2,opt,name=public_raw_base64,json=publicRawBase64,proto3" json:"public_raw_base64,omitempty"`
	TpmHandle       string                 `protobuf:"bytes,3,opt,name=tpm_handle,json=tpmHandle,proto3" json:"tpm_handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetType() PublicKeyType {
	if x != nil {
		return x.Type
	}
	return PublicKeyType_PUBLIC_KEY_TYPE_UNSPECIFIED
}

func (x *PublicKey) GetPublicRawBase64() string {
	if x != nil {
		return x.PublicRawBase64
	}
	return ""
}

func (x *PublicKey) GetTpmHandle() string {
	if x != nil {
		return x.TpmHandle
	}
	return ""
}

// PresentedPublicKey contains public credential material only.
type PresentedPublicKey struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            PublicKeyType          `protobuf:"varint,1,opt,name=type,proto3,enum=sovereignite.v1.PublicKeyType" json:"type,omitempty"`
	PublicRawBase64 string                 `protobuf:"bytes,2,opt,name=public_raw_base64,json=publicRawBase64,proto3" json:"public_raw_base64,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresentedPublicKey) Reset() {
	*x = PresentedPublicKey{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentedPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentedPublicKey) ProtoMessage() {}

func (x *PresentedPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentedPublicKey.ProtoReflect.Descriptor instead.
func (*PresentedPublicKey) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{1}
}

func (x *PresentedPublicKey) GetType() PublicKeyType {
	if x != nil {
		return x.Type
	}
	return PublicKeyType_PUBLIC_KEY_TYPE_UNSPECIFIED
}

func (x *PresentedPublicKey) GetPublicRawBase64() string {
	if x != nil {
		return x.PublicRawBase64
	}
	return ""
}

// CertificateChain contains public X.509 certificate PEM blocks only.
// Implementations must reject private-key and non-certificate PEM blocks.
type CertificateChain struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertificatesPem []string               `protobuf:"bytes,1,rep,name=certificates_pem,json=certificatesPem,proto3" json:"certificates_pem,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateChain) Reset() {
	*x = CertificateChain{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateChain) ProtoMessage() {}

func (x *CertificateChain) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateChain.ProtoReflect.Descriptor instead.
func (*CertificateChain) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{2}
}

func (x *CertificateChain) GetCertificatesPem() []string {
	if x != nil {
		return x.CertificatesPem
	}
	return nil
}

type X509SVID struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CertificateChain *CertificateChain      `protobuf:"bytes,1,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *X509SVID) Reset() {
	*x = X509SVID{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *X509SVID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509SVID) ProtoMessage() {}

func (x *X509SVID) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509SVID.ProtoReflect.Descriptor instead.
func (*X509SVID) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{3}
}

func (x *X509SVID) GetCertificateChain() *CertificateChain {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *X509SVID) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type IdentityCondition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             ConditionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=sovereignite.v1.ConditionStatus" json:"status,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IdentityCondition) Reset() {
	*x = IdentityCondition{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCondition) ProtoMessage() {}

func (x *IdentityCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCondition.ProtoReflect.Descriptor instead.
func (*IdentityCondition) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentityCondition) GetStatus() ConditionStatus {
	if x != nil {
		return x.Status
	}
	return ConditionStatus_CONDITION_STATUS_UNSPECIFIED
}

func (x *IdentityCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdentityCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IdentityCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

type DeviceIdentity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerId             string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Multiaddrs         []string               `protobuf:"bytes,2,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"`
	PublicKeys         []*PublicKey           `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Phase              IdentityPhase          `protobuf:"varint,4,opt,name=phase,proto3,enum=sovereignite.v1.IdentityPhase" json:"phase,omitempty"`
	PeerRecordSequence uint64                 `protobuf:"varint,5,opt,name=peer_record_sequence,json=peerRecordSequence,proto3" json:"peer_record_sequence,omitempty"`
	SpiffeId           string                 `protobuf:"bytes,6,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	X509Svid           *X509SVID              `protobuf:"bytes,7,opt,name=x509_svid,json=x509Svid,proto3" json:"x509_svid,omitempty"`
	Conditions         []*IdentityCondition   `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`
	ObservedGeneration int64                  `protobuf:"varint,9,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceIdentity) Reset() {
	*x = DeviceIdentity{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentity) ProtoMessage() {}

func (x *DeviceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentity.ProtoReflect.Descriptor instead.
func (*DeviceIdentity) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceIdentity) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DeviceIdentity) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *DeviceIdentity) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *DeviceIdentity) GetPhase() IdentityPhase {
	if x != nil {
		return x.Phase
	}
	return IdentityPhase_IDENTITY_PHASE_UNSPECIFIED
}

func (x *DeviceIdentity) GetPeerRecordSequence() uint64 {
	if x != nil {
		return x.PeerRecordSequence
	}
	return 0
}

func (x *DeviceIdentity) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *DeviceIdentity) GetX509Svid() *X509SVID {
	if x != nil {
		return x.X509Svid
	}
	return nil
}

func (x *DeviceIdentity) GetConditions() []*IdentityCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DeviceIdentity) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

type IdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *DeviceIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResponse) Reset() {
	*x = IdentityResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponse) ProtoMessage() {}

func (x *IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponse.ProtoReflect.Descriptor instead.
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityResponse) GetIdentity() *DeviceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type TrustDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrustDomain   string                 `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustDomainResponse) Reset() {
	*x = TrustDomainResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustDomainResponse) ProtoMessage() {}

func (x *TrustDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustDomainResponse.ProtoReflect.Descriptor instead.
func (*TrustDomainResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{7}
}

func (x *TrustDomainResponse) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

// StartBroadcastRequest intentionally has no caller-controlled broadcast
// parameters; the service advertises its configured public identity.
type StartBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBroadcastRequest) Reset() {
	*x = StartBroadcastRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBroadcastRequest) ProtoMessage() {}

func (x *StartBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBroadcastRequest.ProtoReflect.Descriptor instead.
func (*StartBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{8}
}

type DiscoveredDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *DeviceIdentity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	AdoptionState AdoptionState          `protobuf:"varint,2,opt,name=adoption_state,json=adoptionState,proto3,enum=sovereignite.v1.AdoptionState" json:"adoption_state,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredDevice) Reset() {
	*x = DiscoveredDevice{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredDevice) ProtoMessage() {}

func (x *DiscoveredDevice) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredDevice.ProtoReflect.Descriptor instead.
func (*DiscoveredDevice) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoveredDevice) GetIdentity() *DeviceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DiscoveredDevice) GetAdoptionState() AdoptionState {
	if x != nil {
		return x.AdoptionState
	}
	return AdoptionState_ADOPTION_STATE_UNSPECIFIED
}

func (x *DiscoveredDevice) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DiscoveredDevice    `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*DiscoveredDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type TrustRelationship struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	PeerId         string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SpiffeId       string                 `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	TrustDomain    string                 `protobuf:"bytes,4,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	EstablishedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrustRelationship) Reset() {
	*x = TrustRelationship{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustRelationship) ProtoMessage() {}

func (x *TrustRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustRelationship.ProtoReflect.Descriptor instead.
func (*TrustRelationship) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{11}
}

func (x *TrustRelationship) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *TrustRelationship) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *TrustRelationship) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *TrustRelationship) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *TrustRelationship) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

type Federation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemoteTrustDomain string                 `protobuf:"bytes,1,opt,name=remote_trust_domain,json=remoteTrustDomain,proto3" json:"remote_trust_domain,omitempty"`
	EstablishedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Federation) Reset() {
	*x = Federation{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Federation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Federation) ProtoMessage() {}

func (x *Federation) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Federation.ProtoReflect.Descriptor instead.
func (*Federation) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{12}
}

func (x *Federation) GetRemoteTrustDomain() string {
	if x != nil {
		return x.RemoteTrustDomain
	}
	return ""
}

func (x *Federation) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

// The required mTLS transport binds the authenticated adopter identity and
// proof of key possession. peer_id selects the discovered target device.
type AdoptDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptDeviceRequest) Reset() {
	*x = AdoptDeviceRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptDeviceRequest) ProtoMessage() {}

func (x *AdoptDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptDeviceRequest.ProtoReflect.Descriptor instead.
func (*AdoptDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{13}
}

func (x *AdoptDeviceRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type AdoptDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         AdoptionState          `protobuf:"varint,1,opt,name=state,proto3,enum=sovereignite.v1.AdoptionState" json:"state,omitempty"`
	Relationship  *TrustRelationship     `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptDeviceResponse) Reset() {
	*x = AdoptDeviceResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptDeviceResponse) ProtoMessage() {}

func (x *AdoptDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptDeviceResponse.ProtoReflect.Descriptor instead.
func (*AdoptDeviceResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{14}
}

func (x *AdoptDeviceResponse) GetState() AdoptionState {
	if x != nil {
		return x.State
	}
	return AdoptionState_ADOPTION_STATE_UNSPECIFIED
}

func (x *AdoptDeviceResponse) GetRelationship() *TrustRelationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

type TrustRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*TrustRelationship   `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	Federations   []*Federation          `protobuf:"bytes,2,rep,name=federations,proto3" json:"federations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustRelationshipsResponse) Reset() {
	*x = TrustRelationshipsResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustRelationshipsResponse) ProtoMessage() {}

func (x *TrustRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*TrustRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{15}
}

func (x *TrustRelationshipsResponse) GetRelationships() []*TrustRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *TrustRelationshipsResponse) GetFederations() []*Federation {
	if x != nil {
		return x.Federations
	}
	return nil
}

type RevokeTrustRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RelationshipId string                 `protobuf:"bytes,1,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeTrustRequest) Reset() {
	*x = RevokeTrustRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTrustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTrustRequest) ProtoMessage() {}

func (x *RevokeTrustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTrustRequest.ProtoReflect.Descriptor instead.
func (*RevokeTrustRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeTrustRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

type FederateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemoteTrustDomain string                 `protobuf:"bytes,1,opt,name=remote_trust_domain,json=remoteTrustDomain,proto3" json:"remote_trust_domain,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FederateRequest) Reset() {
	*x = FederateRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateRequest) ProtoMessage() {}

func (x *FederateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateRequest.ProtoReflect.Descriptor instead.
func (*FederateRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{17}
}

func (x *FederateRequest) GetRemoteTrustDomain() string {
	if x != nil {
		return x.RemoteTrustDomain
	}
	return ""
}

type FederateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Federation    *Federation            `protobuf:"bytes,1,opt,name=federation,proto3" json:"federation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederateResponse) Reset() {
	*x = FederateResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederateResponse) ProtoMessage() {}

func (x *FederateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederateResponse.ProtoReflect.Descriptor instead.
func (*FederateResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{18}
}

func (x *FederateResponse) GetFederation() *Federation {
	if x != nil {
		return x.Federation
	}
	return nil
}

type BootstrapStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         BootstrapState         `protobuf:"varint,1,opt,name=state,proto3,enum=sovereignite.v1.BootstrapState" json:"state,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapStatus) Reset() {
	*x = BootstrapStatus{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapStatus) ProtoMessage() {}

func (x *BootstrapStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapStatus.ProtoReflect.Descriptor instead.
func (*BootstrapStatus) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{19}
}

func (x *BootstrapStatus) GetState() BootstrapState {
	if x != nil {
		return x.State
	}
	return BootstrapState_BOOTSTRAP_STATE_UNSPECIFIED
}

func (x *BootstrapStatus) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *BootstrapStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BootstrapStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StartBootstrapRequest intentionally has no caller-controlled bootstrap
// parameters; bootstrap consumes the service's validated local configuration.
type StartBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBootstrapRequest) Reset() {
	*x = StartBootstrapRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBootstrapRequest) ProtoMessage() {}

func (x *StartBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBootstrapRequest.ProtoReflect.Descriptor instead.
func (*StartBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{20}
}

type PresentedCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*PresentedCredential_PublicKey
	//	*PresentedCredential_CertificateChain
	Credential    isPresentedCredential_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentedCredential) Reset() {
	*x = PresentedCredential{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentedCredential) ProtoMessage() {}

func (x *PresentedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentedCredential.ProtoReflect.Descriptor instead.
func (*PresentedCredential) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{21}
}

func (x *PresentedCredential) GetCredential() isPresentedCredential_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *PresentedCredential) GetPublicKey() *PresentedPublicKey {
	if x != nil {
		if x, ok := x.Credential.(*PresentedCredential_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *PresentedCredential) GetCertificateChain() *CertificateChain {
	if x != nil {
		if x, ok := x.Credential.(*PresentedCredential_CertificateChain); ok {
			return x.CertificateChain
		}
	}
	return nil
}

type isPresentedCredential_Credential interface {
	isPresentedCredential_Credential()
}

type PresentedCredential_PublicKey struct {
	PublicKey *PresentedPublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type PresentedCredential_CertificateChain struct {
	CertificateChain *CertificateChain `protobuf:"bytes,2,opt,name=certificate_chain,json=certificateChain,proto3,oneof"`
}

func (*PresentedCredential_PublicKey) isPresentedCredential_Credential() {}

func (*PresentedCredential_CertificateChain) isPresentedCredential_Credential() {}

// A presented credential must be bound to the authenticated mTLS session and
// its proof of possession; public material alone is not authorization.
type ValidateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PresentedCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyRequest) Reset() {
	*x = ValidateKeyRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyRequest) ProtoMessage() {}

func (x *ValidateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateKeyRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{22}
}

func (x *ValidateKeyRequest) GetCredential() *PresentedCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type ValidatedIdentity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Subject              string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	PeerId               string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SpiffeId             string                 `protobuf:"bytes,3,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	TrustDomain          string                 `protobuf:"bytes,4,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	PublicKey            *PresentedPublicKey    `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CertificateChain     *CertificateChain      `protobuf:"bytes,6,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	CertificateExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=certificate_expires_at,json=certificateExpiresAt,proto3" json:"certificate_expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ValidatedIdentity) Reset() {
	*x = ValidatedIdentity{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedIdentity) ProtoMessage() {}

func (x *ValidatedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedIdentity.ProtoReflect.Descriptor instead.
func (*ValidatedIdentity) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{23}
}

func (x *ValidatedIdentity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ValidatedIdentity) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ValidatedIdentity) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *ValidatedIdentity) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *ValidatedIdentity) GetPublicKey() *PresentedPublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatedIdentity) GetCertificateChain() *CertificateChain {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

func (x *ValidatedIdentity) GetCertificateExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertificateExpiresAt
	}
	return nil
}

type ValidateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Identity      *ValidatedIdentity     `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyResponse) Reset() {
	*x = ValidateKeyResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyResponse) ProtoMessage() {}

func (x *ValidateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateKeyResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{24}
}

func (x *ValidateKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateKeyResponse) GetIdentity() *ValidatedIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

// The service revalidates this credential and its mTLS binding before asking
// Dex to issue a token.
type IssueJWTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PresentedCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Audience      string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueJWTRequest) Reset() {
	*x = IssueJWTRequest{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueJWTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueJWTRequest) ProtoMessage() {}

func (x *IssueJWTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueJWTRequest.ProtoReflect.Descriptor instead.
func (*IssueJWTRequest) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{25}
}

func (x *IssueJWTRequest) GetCredential() *PresentedCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *IssueJWTRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

// token is opaque to callers; Dex owns its claims and encoding.
type IssueJWTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueJWTResponse) Reset() {
	*x = IssueJWTResponse{}
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueJWTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueJWTResponse) ProtoMessage() {}

func (x *IssueJWTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sovereignite_v1_sovereignite_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueJWTResponse.ProtoReflect.Descriptor instead.
func (*IssueJWTResponse) Descriptor() ([]byte, []int) {
	return file_sovereignite_v1_sovereignite_proto_rawDescGZIP(), []int{26}
}

func (x *IssueJWTResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueJWTResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IssueJWTResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

var File_sovereignite_v1_sovereignite_proto protoreflect.FileDescriptor

const file_sovereignite_v1_sovereignite_proto_rawDesc = "" +
	"\n" +
	"\"sovereignite/v1/sovereignite.proto\x12\x0fsovereignite.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\tPublicKey\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.sovereignite.v1.PublicKeyTypeR\x04type\x12*\n" +
	"\x11public_raw_base64\x18\x02 \x01(\tR\x0fpublicRawBase64\x12\x1d\n" +
	"\n" +
	"tpm_handle\x18\x03 \x01(\tR\ttpmHandle\"t\n" +
	"\x12PresentedPublicKey\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.sovereignite.v1.PublicKeyTypeR\x04type\x12*\n" +
	"\x11public_raw_base64\x18\x02 \x01(\tR\x0fpublicRawBase64\"=\n" +
	"\x10CertificateChain\x12)\n" +
	"\x10certificates_pem\x18\x01 \x03(\tR\x0fcertificatesPem\"\x95\x01\n" +
	"\bX509SVID\x12N\n" +
	"\x11certificate_chain\x18\x01 \x01(\v2!.sovereignite.v1.CertificateChainR\x10certificateChain\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xe1\x01\n" +
	"\x11IdentityCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .sovereignite.v1.ConditionStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12L\n" +
	"\x14last_transition_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\"\xb8\x03\n" +
	"\x0eDeviceIdentity\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x02 \x03(\tR\n" +
	"multiaddrs\x12;\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x1a.sovereignite.v1.PublicKeyR\n" +
	"publicKeys\x124\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x1e.sovereignite.v1.IdentityPhaseR\x05phase\x120\n" +
	"\x14peer_record_sequence\x18\x05 \x01(\x04R\x12peerRecordSequence\x12\x1b\n" +
	"\tspiffe_id\x18\x06 \x01(\tR\bspiffeId\x126\n" +
	"\tx509_svid\x18\a \x01(\v2\x19.sovereignite.v1.X509SVIDR\bx509Svid\x12B\n" +
	"\n" +
	"conditions\x18\b \x03(\v2\".sovereignite.v1.IdentityConditionR\n" +
	"conditions\x12/\n" +
	"\x13observed_generation\x18\t \x01(\x03R\x12observedGeneration\"O\n" +
	"\x10IdentityResponse\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.sovereignite.v1.DeviceIdentityR\bidentity\"8\n" +
	"\x13TrustDomainResponse\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\"\x17\n" +
	"\x15StartBroadcastRequest\"\xd4\x01\n" +
	"\x10DiscoveredDevice\x12;\n" +
	"\bidentity\x18\x01 \x01(\v2\x1f.sovereignite.v1.DeviceIdentityR\bidentity\x12E\n" +
	"\x0eadoption_state\x18\x02 \x01(\x0e2\x1e.sovereignite.v1.AdoptionStateR\radoptionState\x12<\n" +
	"\flast_seen_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"R\n" +
	"\x13ListDevicesResponse\x12;\n" +
	"\adevices\x18\x01 \x03(\v2!.sovereignite.v1.DiscoveredDeviceR\adevices\"\xd8\x01\n" +
	"\x11TrustRelationship\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12!\n" +
	"\ftrust_domain\x18\x04 \x01(\tR\vtrustDomain\x12A\n" +
	"\x0eestablished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\"\x7f\n" +
	"\n" +
	"Federation\x12.\n" +
	"\x13remote_trust_domain\x18\x01 \x01(\tR\x11remoteTrustDomain\x12A\n" +
	"\x0eestablished_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\"-\n" +
	"\x12AdoptDeviceRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\x93\x01\n" +
	"\x13AdoptDeviceResponse\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.sovereignite.v1.AdoptionStateR\x05state\x12F\n" +
	"\frelationship\x18\x02 \x01(\v2\".sovereignite.v1.TrustRelationshipR\frelationship\"\xa5\x01\n" +
	"\x1aTrustRelationshipsResponse\x12H\n" +
	"\rrelationships\x18\x01 \x03(\v2\".sovereignite.v1.TrustRelationshipR\rrelationships\x12=\n" +
	"\vfederations\x18\x02 \x03(\v2\x1b.sovereignite.v1.FederationR\vfederations\"=\n" +
	"\x12RevokeTrustRequest\x12'\n" +
	"\x0frelationship_id\x18\x01 \x01(\tR\x0erelationshipId\"A\n" +
	"\x0fFederateRequest\x12.\n" +
	"\x13remote_trust_domain\x18\x01 \x01(\tR\x11remoteTrustDomain\"O\n" +
	"\x10FederateResponse\x12;\n" +
	"\n" +
	"federation\x18\x01 \x01(\v2\x1b.sovereignite.v1.FederationR\n" +
	"federation\"\xc0\x01\n" +
	"\x0fBootstrapStatus\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.sovereignite.v1.BootstrapStateR\x05state\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\tR\vcurrentStep\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x17\n" +
	"\x15StartBootstrapRequest\"\xbb\x01\n" +
	"\x13PresentedCredential\x12D\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2#.sovereignite.v1.PresentedPublicKeyH\x00R\tpublicKey\x12P\n" +
	"\x11certificate_chain\x18\x02 \x01(\v2!.sovereignite.v1.CertificateChainH\x00R\x10certificateChainB\f\n" +
	"\n" +
	"credential\"Z\n" +
	"\x12ValidateKeyRequest\x12D\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2$.sovereignite.v1.PresentedCredentialR\n" +
	"credential\"\xec\x02\n" +
	"\x11ValidatedIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tspiffe_id\x18\x03 \x01(\tR\bspiffeId\x12!\n" +
	"\ftrust_domain\x18\x04 \x01(\tR\vtrustDomain\x12B\n" +
	"\n" +
	"public_key\x18\x05 \x01(\v2#.sovereignite.v1.PresentedPublicKeyR\tpublicKey\x12N\n" +
	"\x11certificate_chain\x18\x06 \x01(\v2!.sovereignite.v1.CertificateChainR\x10certificateChain\x12P\n" +
	"\x16certificate_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x14certificateExpiresAt\"k\n" +
	"\x13ValidateKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12>\n" +
	"\bidentity\x18\x02 \x01(\v2\".sovereignite.v1.ValidatedIdentityR\bidentity\"s\n" +
	"\x0fIssueJWTRequest\x12D\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2$.sovereignite.v1.PresentedCredentialR\n" +
	"credential\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\"{\n" +
	"\x10IssueJWTResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer*\xa0\x01\n" +
	"\rPublicKeyType\x12\x1f\n" +
	"\x1bPUBLIC_KEY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PUBLIC_KEY_TYPE_RSA\x10\x01\x12\x1b\n" +
	"\x17PUBLIC_KEY_TYPE_ED25519\x10\x02\x12\x1d\n" +
	"\x19PUBLIC_KEY_TYPE_SECP256K1\x10\x03\x12\x19\n" +
	"\x15PUBLIC_KEY_TYPE_ECDSA\x10\x04*\x82\x01\n" +
	"\rIdentityPhase\x12\x1e\n" +
	"\x1aIDENTITY_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16IDENTITY_PHASE_PENDING\x10\x01\x12\x19\n" +
	"\x15IDENTITY_PHASE_ACTIVE\x10\x02\x12\x1a\n" +
	"\x16IDENTITY_PHASE_REVOKED\x10\x03*\x88\x01\n" +
	"\x0fConditionStatus\x12 \n" +
	"\x1cCONDITION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONDITION_STATUS_TRUE\x10\x01\x12\x1a\n" +
	"\x16CONDITION_STATUS_FALSE\x10\x02\x12\x1c\n" +
	"\x18CONDITION_STATUS_UNKNOWN\x10\x03*i\n" +
	"\rAdoptionState\x12\x1e\n" +
	"\x1aADOPTION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ADOPTION_STATE_UNADOPTED\x10\x01\x12\x1a\n" +
	"\x16ADOPTION_STATE_ADOPTED\x10\x02*\xad\x01\n" +
	"\x0eBootstrapState\x12\x1f\n" +
	"\x1bBOOTSTRAP_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBOOTSTRAP_STATE_NOT_STARTED\x10\x01\x12\x1f\n" +
	"\x1bBOOTSTRAP_STATE_IN_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18BOOTSTRAP_STATE_COMPLETE\x10\x03\x12\x1a\n" +
	"\x16BOOTSTRAP_STATE_FAILED\x10\x042\xa4\x01\n" +
	"\bIdentity\x12H\n" +
	"\vGetIdentity\x12\x16.google.protobuf.Empty\x1a!.sovereignite.v1.IdentityResponse\x12N\n" +
	"\x0eGetTrustDomain\x12\x16.google.protobuf.Empty\x1a$.sovereignite.v1.TrustDomainResponse2\xeb\x01\n" +
	"\tDiscovery\x12P\n" +
	"\x0eStartBroadcast\x12&.sovereignite.v1.StartBroadcastRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rStopBroadcast\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\vListDevices\x12\x16.google.protobuf.Empty\x1a$.sovereignite.v1.ListDevicesResponse2\xdc\x02\n" +
	"\x05Trust\x12X\n" +
	"\vAdoptDevice\x12#.sovereignite.v1.AdoptDeviceRequest\x1a$.sovereignite.v1.AdoptDeviceResponse\x12\\\n" +
	"\x15GetTrustRelationships\x12\x16.google.protobuf.Empty\x1a+.sovereignite.v1.TrustRelationshipsResponse\x12J\n" +
	"\vRevokeTrust\x12#.sovereignite.v1.RevokeTrustRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\bFederate\x12 .sovereignite.v1.FederateRequest\x1a!.sovereignite.v1.FederateResponse2\xa4\x01\n" +
	"\tBootstrap\x12E\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a .sovereignite.v1.BootstrapStatus\x12P\n" +
	"\x0eStartBootstrap\x12&.sovereignite.v1.StartBootstrapRequest\x1a\x16.google.protobuf.Empty2\xba\x01\n" +
	"\rKeyValidation\x12X\n" +
	"\vValidateKey\x12#.sovereignite.v1.ValidateKeyRequest\x1a$.sovereignite.v1.ValidateKeyResponse\x12O\n" +
	"\bIssueJWT\x12 .sovereignite.v1.IssueJWTRequest\x1a!.sovereignite.v1.IssueJWTResponseBSZQgithub.com/sovereignite/sovereignite/pkg/api/proto/sovereignite/v1;sovereignitev1b\x06proto3"

var (
	file_sovereignite_v1_sovereignite_proto_rawDescOnce sync.Once
	file_sovereignite_v1_sovereignite_proto_rawDescData []byte
)

func file_sovereignite_v1_sovereignite_proto_rawDescGZIP() []byte {
	file_sovereignite_v1_sovereignite_proto_rawDescOnce.Do(func() {
		file_sovereignite_v1_sovereignite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sovereignite_v1_sovereignite_proto_rawDesc), len(file_sovereignite_v1_sovereignite_proto_rawDesc)))
	})
	return file_sovereignite_v1_sovereignite_proto_rawDescData
}

var file_sovereignite_v1_sovereignite_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sovereignite_v1_sovereignite_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_sovereignite_v1_sovereignite_proto_goTypes = []any{
	(PublicKeyType)(0),                 // 0: sovereignite.v1.PublicKeyType
	(IdentityPhase)(0),                 // 1: sovereignite.v1.IdentityPhase
	(ConditionStatus)(0),               // 2: sovereignite.v1.ConditionStatus
	(AdoptionState)(0),                 // 3: sovereignite.v1.AdoptionState
	(BootstrapState)(0),                // 4: sovereignite.v1.BootstrapState
	(*PublicKey)(nil),                  // 5: sovereignite.v1.PublicKey
	(*PresentedPublicKey)(nil),         // 6: sovereignite.v1.PresentedPublicKey
	(*CertificateChain)(nil),           // 7: sovereignite.v1.CertificateChain
	(*X509SVID)(nil),                   // 8: sovereignite.v1.X509SVID
	(*IdentityCondition)(nil),          // 9: sovereignite.v1.IdentityCondition
	(*DeviceIdentity)(nil),             // 10: sovereignite.v1.DeviceIdentity
	(*IdentityResponse)(nil),           // 11: sovereignite.v1.IdentityResponse
	(*TrustDomainResponse)(nil),        // 12: sovereignite.v1.TrustDomainResponse
	(*StartBroadcastRequest)(nil),      // 13: sovereignite.v1.StartBroadcastRequest
	(*DiscoveredDevice)(nil),           // 14: sovereignite.v1.DiscoveredDevice
	(*ListDevicesResponse)(nil),        // 15: sovereignite.v1.ListDevicesResponse
	(*TrustRelationship)(nil),          // 16: sovereignite.v1.TrustRelationship
	(*Federation)(nil),                 // 17: sovereignite.v1.Federation
	(*AdoptDeviceRequest)(nil),         // 18: sovereignite.v1.AdoptDeviceRequest
	(*AdoptDeviceResponse)(nil),        // 19: sovereignite.v1.AdoptDeviceResponse
	(*TrustRelationshipsResponse)(nil), // 20: sovereignite.v1.TrustRelationshipsResponse
	(*RevokeTrustRequest)(nil),         // 21: sovereignite.v1.RevokeTrustRequest
	(*FederateRequest)(nil),            // 22: sovereignite.v1.FederateRequest
	(*FederateResponse)(nil),           // 23: sovereignite.v1.FederateResponse
	(*BootstrapStatus)(nil),            // 24: sovereignite.v1.BootstrapStatus
	(*StartBootstrapRequest)(nil),      // 25: sovereignite.v1.StartBootstrapRequest
	(*PresentedCredential)(nil),        // 26: sovereignite.v1.PresentedCredential
	(*ValidateKeyRequest)(nil),         // 27: sovereignite.v1.ValidateKeyRequest
	(*ValidatedIdentity)(nil),          // 28: sovereignite.v1.ValidatedIdentity
	(*ValidateKeyResponse)(nil),        // 29: sovereignite.v1.ValidateKeyResponse
	(*IssueJWTRequest)(nil),            // 30: sovereignite.v1.IssueJWTRequest
	(*IssueJWTResponse)(nil),           // 31: sovereignite.v1.IssueJWTResponse
	(*timestamppb.Timestamp)(nil),      // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 33: google.protobuf.Empty
}
var file_sovereignite_v1_sovereignite_proto_depIdxs = []int32{
	0,  // 0: sovereignite.v1.PublicKey.type:type_name -> sovereignite.v1.PublicKeyType
	0,  // 1: sovereignite.v1.PresentedPublicKey.type:type_name -> sovereignite.v1.PublicKeyType
	7,  // 2: sovereignite.v1.X509SVID.certificate_chain:type_name -> sovereignite.v1.CertificateChain
	32, // 3: sovereignite.v1.X509SVID.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 4: sovereignite.v1.IdentityCondition.status:type_name -> sovereignite.v1.ConditionStatus
	32, // 5: sovereignite.v1.IdentityCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	5,  // 6: sovereignite.v1.DeviceIdentity.public_keys:type_name -> sovereignite.v1.PublicKey
	1,  // 7: sovereignite.v1.DeviceIdentity.phase:type_name -> sovereignite.v1.IdentityPhase
	8,  // 8: sovereignite.v1.DeviceIdentity.x509_svid:type_name -> sovereignite.v1.X509SVID
	9,  // 9: sovereignite.v1.DeviceIdentity.conditions:type_name -> sovereignite.v1.IdentityCondition
	10, // 10: sovereignite.v1.IdentityResponse.identity:type_name -> sovereignite.v1.DeviceIdentity
	10, // 11: sovereignite.v1.DiscoveredDevice.identity:type_name -> sovereignite.v1.DeviceIdentity
	3,  // 12: sovereignite.v1.DiscoveredDevice.adoption_state:type_name -> sovereignite.v1.AdoptionState
	32, // 13: sovereignite.v1.DiscoveredDevice.last_seen_at:type_name -> google.protobuf.Timestamp
	14, // 14: sovereignite.v1.ListDevicesResponse.devices:type_name -> sovereignite.v1.DiscoveredDevice
	32, // 15: sovereignite.v1.TrustRelationship.established_at:type_name -> google.protobuf.Timestamp
	32, // 16: sovereignite.v1.Federation.established_at:type_name -> google.protobuf.Timestamp
	3,  // 17: sovereignite.v1.AdoptDeviceResponse.state:type_name -> sovereignite.v1.AdoptionState
	16, // 18: sovereignite.v1.AdoptDeviceResponse.relationship:type_name -> sovereignite.v1.TrustRelationship
	16, // 19: sovereignite.v1.TrustRelationshipsResponse.relationships:type_name -> sovereignite.v1.TrustRelationship
	17, // 20: sovereignite.v1.TrustRelationshipsResponse.federations:type_name -> sovereignite.v1.Federation
	17, // 21: sovereignite.v1.FederateResponse.federation:type_name -> sovereignite.v1.Federation
	4,  // 22: sovereignite.v1.BootstrapStatus.state:type_name -> sovereignite.v1.BootstrapState
	32, // 23: sovereignite.v1.BootstrapStatus.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 24: sovereignite.v1.PresentedCredential.public_key:type_name -> sovereignite.v1.PresentedPublicKey
	7,  // 25: sovereignite.v1.PresentedCredential.certificate_chain:type_name -> sovereignite.v1.CertificateChain
	26, // 26: sovereignite.v1.ValidateKeyRequest.credential:type_name -> sovereignite.v1.PresentedCredential
	6,  // 27: sovereignite.v1.ValidatedIdentity.public_key:type_name -> sovereignite.v1.PresentedPublicKey
	7,  // 28: sovereignite.v1.ValidatedIdentity.certificate_chain:type_name -> sovereignite.v1.CertificateChain
	32, // 29: sovereignite.v1.ValidatedIdentity.certificate_expires_at:type_name -> google.protobuf.Timestamp
	28, // 30: sovereignite.v1.ValidateKeyResponse.identity:type_name -> sovereignite.v1.ValidatedIdentity
	26, // 31: sovereignite.v1.IssueJWTRequest.credential:type_name -> sovereignite.v1.PresentedCredential
	32, // 32: sovereignite.v1.IssueJWTResponse.expires_at:type_name -> google.protobuf.Timestamp
	33, // 33: sovereignite.v1.Identity.GetIdentity:input_type -> google.protobuf.Empty
	33, // 34: sovereignite.v1.Identity.GetTrustDomain:input_type -> google.protobuf.Empty
	13, // 35: sovereignite.v1.Discovery.StartBroadcast:input_type -> sovereignite.v1.StartBroadcastRequest
	33, // 36: sovereignite.v1.Discovery.StopBroadcast:input_type -> google.protobuf.Empty
	33, // 37: sovereignite.v1.Discovery.ListDevices:input_type -> google.protobuf.Empty
	18, // 38: sovereignite.v1.Trust.AdoptDevice:input_type -> sovereignite.v1.AdoptDeviceRequest
	33, // 39: sovereignite.v1.Trust.GetTrustRelationships:input_type -> google.protobuf.Empty
	21, // 40: sovereignite.v1.Trust.RevokeTrust:input_type -> sovereignite.v1.RevokeTrustRequest
	22, // 41: sovereignite.v1.Trust.Federate:input_type -> sovereignite.v1.FederateRequest
	33, // 42: sovereignite.v1.Bootstrap.GetStatus:input_type -> google.protobuf.Empty
	25, // 43: sovereignite.v1.Bootstrap.StartBootstrap:input_type -> sovereignite.v1.StartBootstrapRequest
	27, // 44: sovereignite.v1.KeyValidation.ValidateKey:input_type -> sovereignite.v1.ValidateKeyRequest
	30, // 45: sovereignite.v1.KeyValidation.IssueJWT:input_type -> sovereignite.v1.IssueJWTRequest
	11, // 46: sovereignite.v1.Identity.GetIdentity:output_type -> sovereignite.v1.IdentityResponse
	12, // 47: sovereignite.v1.Identity.GetTrustDomain:output_type -> sovereignite.v1.TrustDomainResponse
	33, // 48: sovereignite.v1.Discovery.StartBroadcast:output_type -> google.protobuf.Empty
	33, // 49: sovereignite.v1.Discovery.StopBroadcast:output_type -> google.protobuf.Empty
	15, // 50: sovereignite.v1.Discovery.ListDevices:output_type -> sovereignite.v1.ListDevicesResponse
	19, // 51: sovereignite.v1.Trust.AdoptDevice:output_type -> sovereignite.v1.AdoptDeviceResponse
	20, // 52: sovereignite.v1.Trust.GetTrustRelationships:output_type -> sovereignite.v1.TrustRelationshipsResponse
	33, // 53: sovereignite.v1.Trust.RevokeTrust:output_type -> google.protobuf.Empty
	23, // 54: sovereignite.v1.Trust.Federate:output_type -> sovereignite.v1.FederateResponse
	24, // 55: sovereignite.v1.Bootstrap.GetStatus:output_type -> sovereignite.v1.BootstrapStatus
	33, // 56: sovereignite.v1.Bootstrap.StartBootstrap:output_type -> google.protobuf.Empty
	29, // 57: sovereignite.v1.KeyValidation.ValidateKey:output_type -> sovereignite.v1.ValidateKeyResponse
	31, // 58: sovereignite.v1.KeyValidation.IssueJWT:output_type -> sovereignite.v1.IssueJWTResponse
	46, // [46:59] is the sub-list for method output_type
	33, // [33:46] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_sovereignite_v1_sovereignite_proto_init() }
func file_sovereignite_v1_sovereignite_proto_init() {
	if File_sovereignite_v1_sovereignite_proto != nil {
		return
	}
	file_sovereignite_v1_sovereignite_proto_msgTypes[21].OneofWrappers = []any{
		(*PresentedCredential_PublicKey)(nil),
		(*PresentedCredential_CertificateChain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sovereignite_v1_sovereignite_proto_rawDesc), len(file_sovereignite_v1_sovereignite_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_sovereignite_v1_sovereignite_proto_goTypes,
		DependencyIndexes: file_sovereignite_v1_sovereignite_proto_depIdxs,
		EnumInfos:         file_sovereignite_v1_sovereignite_proto_enumTypes,
		MessageInfos:      file_sovereignite_v1_sovereignite_proto_msgTypes,
	}.Build()
	File_sovereignite_v1_sovereignite_proto = out.File
	file_sovereignite_v1_sovereignite_proto_goTypes = nil
	file_sovereignite_v1_sovereignite_proto_depIdxs = nil
}
