// SPDX-License-Identifier: GPL-2.0-only
//
// Copyright (C) 2026 Sovereignite contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sovereignite/v1/sovereignite.proto

package sovereignitev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identity_GetIdentity_FullMethodName    = "/sovereignite.v1.Identity/GetIdentity"
	Identity_GetTrustDomain_FullMethodName = "/sovereignite.v1.Identity/GetTrustDomain"
)

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityClient interface {
	GetIdentity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IdentityResponse, error)
	GetTrustDomain(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrustDomainResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) GetIdentity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityResponse)
	err := c.cc.Invoke(ctx, Identity_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) GetTrustDomain(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrustDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustDomainResponse)
	err := c.cc.Invoke(ctx, Identity_GetTrustDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
// All implementations must embed UnimplementedIdentityServer
// for forward compatibility.
type IdentityServer interface {
	GetIdentity(context.Context, *emptypb.Empty) (*IdentityResponse, error)
	GetTrustDomain(context.Context, *emptypb.Empty) (*TrustDomainResponse, error)
	mustEmbedUnimplementedIdentityServer()
}

// UnimplementedIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServer struct{}

func (UnimplementedIdentityServer) GetIdentity(context.Context, *emptypb.Empty) (*IdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedIdentityServer) GetTrustDomain(context.Context, *emptypb.Empty) (*TrustDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustDomain not implemented")
}
func (UnimplementedIdentityServer) mustEmbedUnimplementedIdentityServer() {}
func (UnimplementedIdentityServer) testEmbeddedByValue()                  {}

// UnsafeIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServer will
// result in compilation errors.
type UnsafeIdentityServer interface {
	mustEmbedUnimplementedIdentityServer()
}

func RegisterIdentityServer(s grpc.ServiceRegistrar, srv IdentityServer) {
	// If the following call panics, it indicates UnimplementedIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identity_ServiceDesc, srv)
}

func _Identity_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).GetIdentity(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_GetTrustDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).GetTrustDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identity_GetTrustDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).GetTrustDomain(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Identity_ServiceDesc is the grpc.ServiceDesc for Identity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereignite.v1.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentity",
			Handler:    _Identity_GetIdentity_Handler,
		},
		{
			MethodName: "GetTrustDomain",
			Handler:    _Identity_GetTrustDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereignite/v1/sovereignite.proto",
}

const (
	Discovery_StartBroadcast_FullMethodName = "/sovereignite.v1.Discovery/StartBroadcast"
	Discovery_StopBroadcast_FullMethodName  = "/sovereignite.v1.Discovery/StopBroadcast"
	Discovery_ListDevices_FullMethodName    = "/sovereignite.v1.Discovery/ListDevices"
)

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryClient interface {
	StartBroadcast(ctx context.Context, in *StartBroadcastRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopBroadcast(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDevicesResponse, error)
}

type discoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryClient(cc grpc.ClientConnInterface) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) StartBroadcast(ctx context.Context, in *StartBroadcastRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Discovery_StartBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) StopBroadcast(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Discovery_StopBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, Discovery_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
// All implementations must embed UnimplementedDiscoveryServer
// for forward compatibility.
type DiscoveryServer interface {
	StartBroadcast(context.Context, *StartBroadcastRequest) (*emptypb.Empty, error)
	StopBroadcast(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ListDevices(context.Context, *emptypb.Empty) (*ListDevicesResponse, error)
	mustEmbedUnimplementedDiscoveryServer()
}

// UnimplementedDiscoveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServer struct{}

func (UnimplementedDiscoveryServer) StartBroadcast(context.Context, *StartBroadcastRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBroadcast not implemented")
}
func (UnimplementedDiscoveryServer) StopBroadcast(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopBroadcast not implemented")
}
func (UnimplementedDiscoveryServer) ListDevices(context.Context, *emptypb.Empty) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDiscoveryServer) mustEmbedUnimplementedDiscoveryServer() {}
func (UnimplementedDiscoveryServer) testEmbeddedByValue()                   {}

// UnsafeDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServer will
// result in compilation errors.
type UnsafeDiscoveryServer interface {
	mustEmbedUnimplementedDiscoveryServer()
}

func RegisterDiscoveryServer(s grpc.ServiceRegistrar, srv DiscoveryServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Discovery_ServiceDesc, srv)
}

func _Discovery_StartBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).StartBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Discovery_StartBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).StartBroadcast(ctx, req.(*StartBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_StopBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).StopBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Discovery_StopBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).StopBroadcast(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Discovery_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).ListDevices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Discovery_ServiceDesc is the grpc.ServiceDesc for Discovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Discovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereignite.v1.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBroadcast",
			Handler:    _Discovery_StartBroadcast_Handler,
		},
		{
			MethodName: "StopBroadcast",
			Handler:    _Discovery_StopBroadcast_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _Discovery_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereignite/v1/sovereignite.proto",
}

const (
	Trust_AdoptDevice_FullMethodName           = "/sovereignite.v1.Trust/AdoptDevice"
	Trust_GetTrustRelationships_FullMethodName = "/sovereignite.v1.Trust/GetTrustRelationships"
	Trust_RevokeTrust_FullMethodName           = "/sovereignite.v1.Trust/RevokeTrust"
	Trust_Federate_FullMethodName              = "/sovereignite.v1.Trust/Federate"
)

// TrustClient is the client API for Trust service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrustClient interface {
	AdoptDevice(ctx context.Context, in *AdoptDeviceRequest, opts ...grpc.CallOption) (*AdoptDeviceResponse, error)
	GetTrustRelationships(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrustRelationshipsResponse, error)
	RevokeTrust(ctx context.Context, in *RevokeTrustRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Federate(ctx context.Context, in *FederateRequest, opts ...grpc.CallOption) (*FederateResponse, error)
}

type trustClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustClient(cc grpc.ClientConnInterface) TrustClient {
	return &trustClient{cc}
}

func (c *trustClient) AdoptDevice(ctx context.Context, in *AdoptDeviceRequest, opts ...grpc.CallOption) (*AdoptDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptDeviceResponse)
	err := c.cc.Invoke(ctx, Trust_AdoptDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustClient) GetTrustRelationships(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TrustRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustRelationshipsResponse)
	err := c.cc.Invoke(ctx, Trust_GetTrustRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustClient) RevokeTrust(ctx context.Context, in *RevokeTrustRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Trust_RevokeTrust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustClient) Federate(ctx context.Context, in *FederateRequest, opts ...grpc.CallOption) (*FederateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FederateResponse)
	err := c.cc.Invoke(ctx, Trust_Federate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustServer is the server API for Trust service.
// All implementations must embed UnimplementedTrustServer
// for forward compatibility.
type TrustServer interface {
	AdoptDevice(context.Context, *AdoptDeviceRequest) (*AdoptDeviceResponse, error)
	GetTrustRelationships(context.Context, *emptypb.Empty) (*TrustRelationshipsResponse, error)
	RevokeTrust(context.Context, *RevokeTrustRequest) (*emptypb.Empty, error)
	Federate(context.Context, *FederateRequest) (*FederateResponse, error)
	mustEmbedUnimplementedTrustServer()
}

// UnimplementedTrustServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrustServer struct{}

func (UnimplementedTrustServer) AdoptDevice(context.Context, *AdoptDeviceRequest) (*AdoptDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdoptDevice not implemented")
}
func (UnimplementedTrustServer) GetTrustRelationships(context.Context, *emptypb.Empty) (*TrustRelationshipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrustRelationships not implemented")
}
func (UnimplementedTrustServer) RevokeTrust(context.Context, *RevokeTrustRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeTrust not implemented")
}
func (UnimplementedTrustServer) Federate(context.Context, *FederateRequest) (*FederateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Federate not implemented")
}
func (UnimplementedTrustServer) mustEmbedUnimplementedTrustServer() {}
func (UnimplementedTrustServer) testEmbeddedByValue()               {}

// UnsafeTrustServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustServer will
// result in compilation errors.
type UnsafeTrustServer interface {
	mustEmbedUnimplementedTrustServer()
}

func RegisterTrustServer(s grpc.ServiceRegistrar, srv TrustServer) {
	// If the following call panics, it indicates UnimplementedTrustServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trust_ServiceDesc, srv)
}

func _Trust_AdoptDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServer).AdoptDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trust_AdoptDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServer).AdoptDevice(ctx, req.(*AdoptDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trust_GetTrustRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServer).GetTrustRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trust_GetTrustRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServer).GetTrustRelationships(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trust_RevokeTrust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTrustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServer).RevokeTrust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trust_RevokeTrust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServer).RevokeTrust(ctx, req.(*RevokeTrustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trust_Federate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FederateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustServer).Federate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trust_Federate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustServer).Federate(ctx, req.(*FederateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trust_ServiceDesc is the grpc.ServiceDesc for Trust service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trust_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereignite.v1.Trust",
	HandlerType: (*TrustServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdoptDevice",
			Handler:    _Trust_AdoptDevice_Handler,
		},
		{
			MethodName: "GetTrustRelationships",
			Handler:    _Trust_GetTrustRelationships_Handler,
		},
		{
			MethodName: "RevokeTrust",
			Handler:    _Trust_RevokeTrust_Handler,
		},
		{
			MethodName: "Federate",
			Handler:    _Trust_Federate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereignite/v1/sovereignite.proto",
}

const (
	Bootstrap_GetStatus_FullMethodName      = "/sovereignite.v1.Bootstrap/GetStatus"
	Bootstrap_StartBootstrap_FullMethodName = "/sovereignite.v1.Bootstrap/StartBootstrap"
)

// BootstrapClient is the client API for Bootstrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BootstrapClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BootstrapStatus, error)
	StartBootstrap(ctx context.Context, in *StartBootstrapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type bootstrapClient struct {
	cc grpc.ClientConnInterface
}

func NewBootstrapClient(cc grpc.ClientConnInterface) BootstrapClient {
	return &bootstrapClient{cc}
}

func (c *bootstrapClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BootstrapStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapStatus)
	err := c.cc.Invoke(ctx, Bootstrap_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapClient) StartBootstrap(ctx context.Context, in *StartBootstrapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Bootstrap_StartBootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootstrapServer is the server API for Bootstrap service.
// All implementations must embed UnimplementedBootstrapServer
// for forward compatibility.
type BootstrapServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*BootstrapStatus, error)
	StartBootstrap(context.Context, *StartBootstrapRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBootstrapServer()
}

// UnimplementedBootstrapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBootstrapServer struct{}

func (UnimplementedBootstrapServer) GetStatus(context.Context, *emptypb.Empty) (*BootstrapStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBootstrapServer) StartBootstrap(context.Context, *StartBootstrapRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBootstrap not implemented")
}
func (UnimplementedBootstrapServer) mustEmbedUnimplementedBootstrapServer() {}
func (UnimplementedBootstrapServer) testEmbeddedByValue()                   {}

// UnsafeBootstrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootstrapServer will
// result in compilation errors.
type UnsafeBootstrapServer interface {
	mustEmbedUnimplementedBootstrapServer()
}

func RegisterBootstrapServer(s grpc.ServiceRegistrar, srv BootstrapServer) {
	// If the following call panics, it indicates UnimplementedBootstrapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bootstrap_ServiceDesc, srv)
}

func _Bootstrap_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bootstrap_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bootstrap_StartBootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapServer).StartBootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bootstrap_StartBootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapServer).StartBootstrap(ctx, req.(*StartBootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bootstrap_ServiceDesc is the grpc.ServiceDesc for Bootstrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bootstrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereignite.v1.Bootstrap",
	HandlerType: (*BootstrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Bootstrap_GetStatus_Handler,
		},
		{
			MethodName: "StartBootstrap",
			Handler:    _Bootstrap_StartBootstrap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereignite/v1/sovereignite.proto",
}

const (
	KeyValidation_ValidateKey_FullMethodName = "/sovereignite.v1.KeyValidation/ValidateKey"
	KeyValidation_IssueJWT_FullMethodName    = "/sovereignite.v1.KeyValidation/IssueJWT"
)

// KeyValidationClient is the client API for KeyValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValidationClient interface {
	ValidateKey(ctx context.Context, in *ValidateKeyRequest, opts ...grpc.CallOption) (*ValidateKeyResponse, error)
	IssueJWT(ctx context.Context, in *IssueJWTRequest, opts ...grpc.CallOption) (*IssueJWTResponse, error)
}

type keyValidationClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValidationClient(cc grpc.ClientConnInterface) KeyValidationClient {
	return &keyValidationClient{cc}
}

func (c *keyValidationClient) ValidateKey(ctx context.Context, in *ValidateKeyRequest, opts ...grpc.CallOption) (*ValidateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateKeyResponse)
	err := c.cc.Invoke(ctx, KeyValidation_ValidateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValidationClient) IssueJWT(ctx context.Context, in *IssueJWTRequest, opts ...grpc.CallOption) (*IssueJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueJWTResponse)
	err := c.cc.Invoke(ctx, KeyValidation_IssueJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValidationServer is the server API for KeyValidation service.
// All implementations must embed UnimplementedKeyValidationServer
// for forward compatibility.
type KeyValidationServer interface {
	ValidateKey(context.Context, *ValidateKeyRequest) (*ValidateKeyResponse, error)
	IssueJWT(context.Context, *IssueJWTRequest) (*IssueJWTResponse, error)
	mustEmbedUnimplementedKeyValidationServer()
}

// UnimplementedKeyValidationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValidationServer struct{}

func (UnimplementedKeyValidationServer) ValidateKey(context.Context, *ValidateKeyRequest) (*ValidateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateKey not implemented")
}
func (UnimplementedKeyValidationServer) IssueJWT(context.Context, *IssueJWTRequest) (*IssueJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueJWT not implemented")
}
func (UnimplementedKeyValidationServer) mustEmbedUnimplementedKeyValidationServer() {}
func (UnimplementedKeyValidationServer) testEmbeddedByValue()                       {}

// UnsafeKeyValidationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValidationServer will
// result in compilation errors.
type UnsafeKeyValidationServer interface {
	mustEmbedUnimplementedKeyValidationServer()
}

func RegisterKeyValidationServer(s grpc.ServiceRegistrar, srv KeyValidationServer) {
	// If the following call panics, it indicates UnimplementedKeyValidationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyValidation_ServiceDesc, srv)
}

func _KeyValidation_ValidateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValidationServer).ValidateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValidation_ValidateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValidationServer).ValidateKey(ctx, req.(*ValidateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValidation_IssueJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValidationServer).IssueJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValidation_IssueJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValidationServer).IssueJWT(ctx, req.(*IssueJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyValidation_ServiceDesc is the grpc.ServiceDesc for KeyValidation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValidation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovereignite.v1.KeyValidation",
	HandlerType: (*KeyValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateKey",
			Handler:    _KeyValidation_ValidateKey_Handler,
		},
		{
			MethodName: "IssueJWT",
			Handler:    _KeyValidation_IssueJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sovereignite/v1/sovereignite.proto",
}
