apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tpm-cluster-issuer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tpm-cluster-issuer
subjects:
  - kind: ServiceAccount
    name: tpm-cluster-issuer
    namespace: sovereignite-system
