# Source apiVersion: rbac.authorization.k8s.io/v1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: activator
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.22.1
  name: knative-serving-activator
  namespace: knative-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knative-serving-activator
subjects:
  - kind: ServiceAccount
    name: activator
    namespace: knative-serving
