name: Build keymanager

on:
  push:
    branches: [main]
    paths:
      - 'cmd/keymanager/**'
      - 'internal/keymanager/**'
      - 'internal/tpm/**'
      - 'internal/shared/**'
      - 'internal/endpoint/**'
      - '.ko.yaml'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/*keymanager*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-service.yaml
    with:
      build: keymanager
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
