apiVersion: pki.sovereignite.io/v1alpha1
kind: TPMClusterIssuer
metadata:
  name: spire-tpm-devid-ca
spec:
  caRef:
    name: spire-tpm-devid-ca
  pkcs11:
    keyLabel: sovereignite-spire-tpm-devid-ca
    modulePath: /usr/lib64/pkcs11/libtpm2_pkcs11.so
    tokenLabel: sovereignite-ca
    userPinSecretRef:
      key: user-pin
      name: tpm2-pkcs11-pin
      namespace: sovereignite-system
  profiles:
    default:
      maxDuration: 2160h
      usages:
      - digital signature
      - key encipherment
      - server auth
      - client auth
  requestPolicy:
    denyCARequests: true
    requireApprovedCondition: true
  signerName: tpmclusterissuers.pki.sovereignite.io/spire-tpm-devid-ca
