apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/name: cert-manager
  name: cert-manager-controller-approve:pki-sovereignite-io
rules:
- apiGroups:
  - cert-manager.io
  resourceNames:
  - tpmclusterissuers.pki.sovereignite.io/sovereignite-root
  - tpmclusterissuers.pki.sovereignite.io/kubernetes-ca
  - tpmclusterissuers.pki.sovereignite.io/kubernetes-front-proxy-ca
  - tpmclusterissuers.pki.sovereignite.io/etcd-ca
  - tpmclusterissuers.pki.sovereignite.io/cert-manager-local-ca
  - tpmclusterissuers.pki.sovereignite.io/spire-upstream-ca
  - tpmclusterissuers.pki.sovereignite.io/spire-tpm-devid-ca
  - tpmclusterissuers.pki.sovereignite.io/spire-tpm-endorsement-ca
  resources:
  - signers
  verbs:
  - approve
